AtlasOfLivingAustralia/ala-install

.gitignore
ansible/callback_plugins/machine_audit_callback.py
ansible/library/machine_audit.py
ansible/machine_audit.yml

This adds "machine audit", which consists of a playbook, an inventory, a callback plugin and a module.  It gathers facts about servers and outputs a .csv file (in the machine_audit dir) with the results.
Soon to come:
- get Tomcat 5 info (currently only 6 and 7)
- get Solr info

machine audit v1

---

ansible/roles/tomcat_deploy/tasks/main.yml

Hi guys,
When playing with the last version of the Ansible scripts, I noticed errors because Tomcat deploy launch the new backup task unconditionally. This fails the first time, since there's no war file to copy.
I seems this patch fix the issue, but I'm very new to Ansible.

Tomcat deploy task doesn't try to backup inexistent files anymore.

---

README.md

The PPA that was referenced is currently hosting ansible-2.0, and may bump to ansible-2.1 in the near future. Checking out ansible-1.8.4 from Git is the safest way to ensure that it is used consistently instead of the newer versions.

Change Ansible instructions to install from PIP

---

ansible/roles/cassandra/templates/cassandra.yaml

This Pull Request is to track changes to the cassandra-1.2 configuration to prevent it getting bottlenecked on cassandra-b4. Cassandra was bottlenecked multiple times in the past 2-3 weeks during both processing (loading) and reindexing.
The following are some JMX traces obtained that illustrate the times where Cassandra bottlenecks and is unable to release memory when the stack becomes 99.99% full, but generally continues to do attempt to do so instead of crashing. In order to also track the Solr activity when crashes occurred, some of the screen shots below also include the solr-b3 JMX heap traces. They are distinguishable based on the heap size, as Solr has a 90+GB heap, where Cassandra has a less than 20GB heap:
Not all of these changes have actually been tested yet, but they are …

Tuning for cassandra

---

ansible/amrin-hub-standalone.yml
ansible/asbp-hub-standalone.yml
ansible/ozcam-hub-standalone.yml
ansible/roles/tomcat7-java8/defaults/main.yml
ansible/roles/tomcat7-java8/handlers/main.yml
ansible/roles/tomcat7-java8/meta/main.yml
ansible/roles/tomcat7-java8/tasks/main.yml
ansible/roles/tomcat7-java8/vars/main.yml

Deploying these three thin hubs required updating them to Java-8 per the removal of the Oracle Java-7 JDK from unauthenticated access and the lack of OpenJDK-7 in Ubuntu-16.04.
I wasn't able to completely automate the process, as the apt-get install for tomcat7 failed when restarting tomcat and didn't allow ansible to proceed until I manually edited the /etc/default/tomcat7 file to add the desired JAVA_HOME location.
At least one suggested solution for this is just to always edit the file yourself, but not sure how it could otherwise be automated, as it fails during the ansible call to "apt-get install tomcat7", and the /etc/default/tomcat7 file is not present before that call, so not clear how you could otherwise edit it using an automated script. …

Add a new Tomcat7 java8 role used by OZCAM, AMRIN, and ASBP

---

ansible/collectory-standalone.yml
ansible/roles/java8/tasks/main.yml
ansible/roles/mysql-5.7/handlers/main.yml
ansible/roles/mysql-5.7/tasks/main.yml
ansible/roles/mysql-5.7/templates/my.cnf
ansible/roles/nameindex/tasks/main.yml

Fixes #131 , #132 and #133 to get collectory-test deploying successfully to ubuntu 16.04. This does not include the collectory code changes that @charvolant is doing separately, it only includes ansible changes necessary to get the ansible scripts running again.

Deploy collectory-test with mysql-5.7

---

ansible/roles/biocache-hub/templates/config/config.properties

This small patch allow to use different urls for you layers and/or geoserver service if they are different from `spatial_base_url`.
If `layers_base_url` is not defined it uses `spatial_base_url` as before, etc. Same with `map_overlay_base_url`.

More configurable maps and layers urls

---

ansible/regions-mdba-standalone.yml
ansible/roles/biocache-hub/templates/config/grouped_facets_mdba.json
ansible/roles/regions/templates/menu-config-mdba.json

The new mdba layers need changes to both `mdba-hub` and `mdba-regions`:
https://github.com/AtlasOfLivingAustralia/layers-service/issues/105
This Pull Request is to pull those together without updating master until they are working, as updating before then causes the entire site to fail due to the way the groovy code is implemented in `mdba-hub`/`biocache-hubs`
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>

The necessary layers updates for mdba

---

ansible/inventories/workshop/demo-livingatlas.yml

Test clearing vhost fragments for demo.livingatlas.org
It is possible that the cause of issue #253 was a change in the name of the fragment file. The only known fix for this is to clear the vhost fragments completely at the start of the ansible run.
IMPORTANT: This unfortunately breaks the ability to use tags to skip any `nginx_vhost` role calls as doing so will result in an incomplete nginx configuration.
CC @vjrj

issue #253 : Test clearing vhost fragments

---

ansible/roles/biocache-service/tasks/main.yml

If you are not using a subdomain like `biocache-ws.hello.com` but you are using a context-path like `data.hello.com/biocache-ws`, on line 229 "/biocache-download" will failed

Update download url in nginx

---

ansible/inventories/living-atlas

Removed `name_index_dir` from demo inventory so configures `biocache-service` to use:
```
name.index.dir=/data/lucene/namematching
```
default value instead of:
```
name.index.dir=/data/lucene/namematching/namematching
```
after #222 fix.

Use def namematching directory in demo inventory after #222 fix

---

ansible/roles/biocache-properties/templates/biocache-config.properties

Same here, `bie_service_url` and `bie_url` is not used in demo&workshop inventories:
```
$ egrep "bie_service_url|bie_url" ansible/inventories/living-atlas ansible/inventories/workshop/demo-livingatlas.yml
$ echo $?
1
$ egrep "bie_service_base_url|bie_base_url" ansible/inventories/living-atlas ansible/inventories/workshop/demo-livingatlas.yml
ansible/inventories/living-atlas:bie_service_base_url = http://living-atlas.org/bie-index
ansible/inventories/living-atlas:bie_base_url = http://living-atlas.org/ala-bie
ansible/inventories/workshop/demo-livingatlas.yml:bie_service_base_url=http://demo.livingatlas.org/bie-index
ansible/inventories/workshop/demo-livingatlas.yml:bie_base_url=http://demo.livingatlas.org/ala-bie
ansible/inventories/workshop/demo-livingatlas.yml:bie_base_url = …
```

Consistent bie vars with demo&workshop inventories

---

ansible/roles/biocache-hub/templates/config/config.properties
ansible/roles/collectory/templates/config/collectory-config.properties

Added `logger_webservice_url` used in demo&workshop playbooks trying to not break things in other playbooks that do not use this var.

Consistent logger vars with demo&workshop playbooks

---

ansible/roles/image-service/templates/config/config.properties

`biocache_url` is not used in demo and workshop inventories but `biocache_hub_url` so I added trying to not to break other inventories.
```
$ grep biocache_hub_url ansible/inventories/workshop/demo-livingatlas.yml ansible/inventories/living-atlas
ansible/inventories/workshop/demo-livingatlas.yml:biocache_hub_url = http://demo.livingatlas.org/ala-hub
ansible/inventories/living-atlas:biocache_hub_url = http://living-atlas.org/ala-hub
$ grep biocache_url ansible/inventories/workshop/demo-livingatlas.yml ansible/inventories/living-atlas 
$ echo $?
1
```

Consistent ala-hub var with demo & workshop inventories

---

ansible/roles/biocache-db/tasks/main.yml

`swapoff` fails in LXC containers so we can skip this task.

Skip swapoff in LXC containers

---

ansible/roles/alerts/templates/alerts-config.properties

Otherwise userdetails-service-client defaults to using auth.ala.org.au/userdetails which fails for non-ALA setups, locking all users in the alerts database.

Include userdetails url

---

ansible/roles/cas-management/templates/application.properties

The current configuration with `cas-management` `5.3.1-1-SNAPSHOT` fails with errors like:
```
mgmt[userPropertiesFile is not readable or has an invalid getter method
```
renaming that params `cas-management` starts without errors.

Fix some configuration names that makes cas-management not to start

---

ansible/roles/collectory/templates/config/collectory-config.properties

Added some CAS login/logout urls to collectory config so its not redirect to `auth.ala.org.au` in non-ALA nodes using CAS.

Added login/logout CAS urls to collectory config

---

ansible/roles/biocache-properties/templates/biocache-config.properties

Just adding this email variables to `ala-install`:
https://github.com/AtlasOfLivingAustralia/biocache-service/blob/9f08a35b6b3735af5c69eace2d882a4bc367112d/src/main/java/au/org/ala/biocache/service/EmailService.java

email download vars added to biocache template

---

ansible/roles/spatial-hub/vars/main.yml
ansible/roles/spatial-service/vars/main.yml

We get a 404 errors when trying to configure spatial in a demo for Tanzania:
```
TASK [spatial-service : download from maven repo] **********************************************************************************************************************│····················
fatal: [spatial.tanbif.or.tz]: FAILED! => {"changed": false, "dest": "/var/lib/tomcat7/webapps-spatial.tanbif.or.tz/ws.war", "elapsed": 2, "msg": "Request failed", "res│····················
ponse": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://nexus.ala.org.au/service/local/artifact/maven/redirect?r=public&g=au.org.ala&a=spatial-service&│····················
v=0.3-SNAPSHOT&e=war&c="}  
```

Use spatial 0.3 just released to prevent 404 when using old snapshots

---

ansible/roles/geoserver/tasks/main.yml

When using self-signed certs the `geoserver` uri check task fails. Adding this var I can install the spatial playbook correctly using this `ssl` certs.
This is part of a plan to add `ssl` support to the yeoman generator, so it's more easy to configure ssl in new nodes.
I can improve this PR adding a new variable like `ssl_validate_certs` that defaults to `true`, that is the default uri behavior:
https://docs.ansible.com/ansible/latest/modules/uri_module.html
if you prefer...

Allow self-signed certs in geoserver check

---

ansible/cas5-standalone.yml

A basic repo update to prevent 404 errors trying to install redis from official repo.
```
fatal: [auth.living-atlas.org]: FAILED! => {"cache_update_time": 1559583292, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'redis-server'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/r/redis/redis-tools_4.0.9-1ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.88.31 80]\nE: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/r/redis/redis-server_4.0.9-1ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.88.31 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch …
```

Fix apt update so redis install don't give 404

---

ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/tasks/postgis.yml

After https://github.com/AtlasOfLivingAustralia/ala-install/commit/f079973be51fe2c198c89d67eaa4bcbac2526ccf new `postgis` var check fails with:
```
fatal: [core.biodiversityatlas.at]: FAILED! => {"msg": "The conditional check 'postgis_version is defined and postgis_version | length > 0' failed. The error was: Unexpected templating type error occurred on ({% if postgis_version is defined and postgis_version | length > 0 %} True {% else %} False {% endif %}): object of type 'float' has no len()\n\nThe error appears to be in '/home/ubuntu/Desktop/bio.at/ala-install/ansible/roles/postgresql/tasks/postgis.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: install setfacl support\n  ^ here\n"}
```
or …

Fix postgis var definition checks

---

ansible/roles/demo/templates/banner.html
ansible/roles/demo/templates/index.html

When running the demo role but using multiple subdomains and hosts, demo index and header urls are wrong because they only use `context_path`.
See links in:
https://core.biodiversityatlas.at
and header of:
https://collectory.biodiversityatlas.at/
This patch uses the full base url of each services to fix this.
cc @geonb

Use full url instead of context path in demo

---

ansible/cas5-standalone.yml

After installing CAS in a new server CAS service don't start, I see that is because java is not installed:
```
root@auth:/var/log/atlas# /opt/atlas/cas/cas.jar
Unable to find Java
```
and this was removed from the last CAS roles refactorization.

Include again common and java role in CAS

---

ansible/inventories/living-atlas-cas-5

After this commit https://github.com/AtlasOfLivingAustralia/apikey/commit/edff128fa799e3905f2276dde308e3163e4b6f11
this db initialization I used as a workaround is not needed anymore.

Removed apikey mysql init dump after flyway fix in apikey module

---

ansible/cas5-standalone.yml

After the last CAS update, mongo users are not created by default in new CAS servers because the new variable `cas_add_mongo_users` is not configured. So the `cas` and related services fails to start on first deploy.

Add mongodb users by default

---

ansible/roles/logger-service/templates/logger-config.properties
ansible/roles/species-list/templates/specieslist-webapp-config.properties

Minor change to use the same logger webservice url and new CAS vars than other roles, with backward compatibility.

Standardize vars in specieslist and logger

---

ansible/aws-cas-5.yml
ansible/cas5-standalone.yml
ansible/roles/mongodb-org/tasks/main.yml

The mongo users were not created by default with https://github.com/AtlasOfLivingAustralia/ala-install/pull/318 because the var is not correctly configured. See: 
```
TASK [mongodb_user] *************************************************************************************************************************************************************************
skipping: [auth.vtatlasoflife.org] => (item={u'login_port': u'27017', u'roles': u'readWrite', u'database': u'cas-ticket-registry', u'login_user': u'admin', u'login_host': u'localhost', u'loskipping: [auth.vtatlasoflife.org] => (item={u'login_port': u'27017', u'roles': u'readWrite', u'database': u'cas-service-registry', u'login_user': u'admin', u'login_host': u'localhost', u'login_password': u'password', u'ssl': u'false', u'user': …
```

CAS mongo users creation proper fix

---

ansible/roles/bie-hub/templates/bie-hub-config.properties
ansible/roles/bie-index/templates/bie-index-config.yml

Minor change to use the same base urls than other roles, with backward compatibility.
Org name configurable when yml configuration used.

Standardize logger webservice url in specieslist

---

ansible/ala-demo.yml
ansible/roles/image-service/defaults/main.yml
ansible/roles/image-service/tasks/main.yml
ansible/roles/image-service/templates/config/image-service-config.yml

To not conflict with tomcat 8080 port we set some default port for image service in the demo playbook but also in the service configuration (so embedded tomcat not uses 8080 by default).
PS: I updated also the generator  to use the new image service:
https://github.com/vjrj/generator-living-atlas/commit/2ac96bd68498e739c8b9c292d03f48166713e102

Set images port in demo playbook and service configuration

---

ansible/ala-demo-basic.yml

A basic demo playbook without services (only webserver), for using in
https://github.com/vjrj/generator-living-atlas with multiple hosts, so each service is installed in the selected hostname.

Basic ala-demo playbook with only webserver task

---

ansible/roles/demo/tasks/main.yml

I added a task to configure the main vhost in demo.
This is only useful when you run a demo with only subdomains.example.org for services when no example.org/context/ services are configured (this is the cause of #322).

Add vhost for demo /srv location. Fix #322

---

ansible/roles/webapi_instance/templates/webapi-config.properties
ansible/roles/webapi_instance/vars/main.yml
ansible/webapi_standalone.yml

I've updated the webapi role to install https://api.gbif.es
I updated also the ansible generator to support webapi service, so other portals can use it also: https://github.com/vjrj/generator-living-atlas/commit/788a8698dcfba41abd2950d708915e6f84a4047c
So I update that role with the problems I found (CAS issues, old mysql version, old war used, etc).

Update webapi role

---

ansible/roles/species-list/templates/specieslist-webapp-config.properties

After this https://github.com/AtlasOfLivingAustralia/ala-install/commit/cda6a5c4209f6e248fc86c1c3de5d06ff72fbb26 commit to prevent this error:
```
fatal: [xxxxx]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'specieslist_authenticate_only_if_logged_in_filter_pattern' is undefined"}
```

Set default value for authenticateOnlyIfLoggedInFilterPattern in specieslists role

---

ansible/ala-demo-basic.yml

I add java and tomcat role to the `ala-demo-basic` playbook, as the demo role uses [tomcat user in some task](https://github.com/AtlasOfLivingAustralia/ala-install/blob/fac927e5e78d650c83da52ef5e98b1a8f07152a5/ansible/roles/demo/tasks/main.yml#L9).

Added tomcat dep to ala-demo-basic

---

ansible/roles/species-list/templates/specieslist-webapp-config.properties

Some additional vars in species lists role. One is to prevent some:
`Unable to obtain species details from BIE - Read timed out`
configuring [this var](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/blob/d4c0cb4f02bf79718dec0b9246b6706175182393/grails-app/conf/application.yml#L159).

Additional vars in specieslists role

---

ansible/roles/demo/templates/index.html

Currently the role generates this url in the `index.html`:
`<a href="http://http://index.gbif.pt:8983">Apache SOLR</a>`

Fix solr url in demo role

---

ansible/collectory-standalone.yml
ansible/roles/i18n/tasks/main.yml
ansible/species-list-standalone.yml

Now that [my ala-i18n PRs are merged](https://github.com/search?q=is%3Apr+author%3Avjrj+org%3AAtlasOfLivingAustralia+ala-i18n+external&type=Issues) I created a simple i18n role to install the [ala-i18n package](https://github.com/living-atlases/ala-i18n).
It will be nice that in some moment this repository, and jenkins jobs are transferred to ALA.

Added i18n role with ala-i18n package

---

ansible/roles/biocache-hub/templates/config/config.properties

Without default values we have some errors like:
``` 
fatal: [records.no.l-a.site]: FAILED! => {“changed”: false, “msg”: “AnsibleUndefinedVariable: ‘specieslist_uid’ is undefined”}
``` 
PS: Thanks to Rukaya from gbif.no for the feedback.

Added missing default values for mdba list

---

ansible/roles/nginx_vhost/defaults/main.yml
ansible/roles/nginx_vhost/tasks/main.yml

I rewrote this https://github.com/AtlasOfLivingAustralia/ala-install/pull/366 following @ansell suggestion.
I tested in a demo site and with `true` in the new var `vhost_with_appname_conf` and I get:
```
biocache.l-a.site-ala-hub.conf
biocache.l-a.site-biocache-service.conf
```
as expected.

Prevent overwrite vhost configurations when deploying in same server (rewritten with appname)

---

ansible/roles/i18n/tasks/main.yml

@jloomisVCE (Vermont) just send me a report of a error running the just merged `ala-i18n` role.
```
ASK [i18n : Install ala-i18n apt repository] ************************************************************************
fatal: [lists.vtatlasoflife.org]: FAILED! => {"changed": false, "module_stderr": "Shared connection to A.B.C.D closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1581363307.91-152234570568148/AnsiballZ_apt_repository.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1581363307.91-152234570568148/AnsiballZ_apt_repository.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File …
```

Correct order of tasks in ala-i18n role

---

ansible/aws-cas-5.yml

Without default values we have some errors like:
``` 
fatal: [auth.no.l-a.site]: FAILED! => {“msg”: “‘cas_audit_host’ is undefined”}
``` 
PS: Thanks to Rukaya from gbif.no for the feedback.

Added missing default values for CAS audit

---

ansible/roles/image-service/tasks/main.yml

After https://github.com/AtlasOfLivingAustralia/ala-install/pull/368 we need to set missing `appname` in `image-service` as in the rest of roles, to prevent these kind of errors:
```
fatal: [imagenes.snib.conap.gob.gt]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'appname' is undefined\n\nThe error appears to be in '/home/gt/ala-install/ansible/roles/nginx_vhost/tasks/main.yml'
```

Added missing appname in image-service

---

ansible/roles/cassandra3/tasks/main.yml

Running cassandra3 role, we experienced some errors related with the gpg keys:
```
fatal: [biocache-store.snib.conap.gob.gt]: FAILED! => {"changed": true, "cmd": "curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -", "delta": "0:00:02.277836", "end": "2020-02-27 16:55:39.955248", "msg": "non-zero return code", "rc": 2, "start": "2020-02-27 16:55:37.677412", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\r100   227  100   227    0     0    100      0  0:00:02  0:00:02 --:--:--   100\ngpg: no valid OpenPGP data found.", "stderr_lines": ["  % Total    % Received % Xferd  Average …
```

Fix cassandra keys url

---

ansible/roles/spatial-hub/tasks/main.yml
ansible/roles/spatial-service/tasks/main.yml

After https://github.com/AtlasOfLivingAustralia/ala-install/pull/368 we need to set missing `appname` in some tasks of`spatial-hub` and `spatial-service`.

Added missing appname to spatial-hub and spatial-service roles

---

ansible/roles/cassandra3/tasks/main.yml

This week in Vermont, when they were updating their LA deployment to new LA versions, the cassandra role wiped all its data after rerun it.
https://github.com/AtlasOfLivingAustralia/ala-install/blob/d610dceee1b85ea494fa66c83af63d0025fdc23a/ansible/roles/cassandra3/tasks/main.yml#L103
This patch tries to prevent this to happen again but also to rerun the cassandra role safely (for upgrades).
Take into account that many LA deployments right now doesn't have a cassandra or solr cluster.
To detect if the cassandra remove task should be executed or not, I use a simple initial detection of the cassandra package installation status. 
If the cassandra package is the fist time is installed, the rm task is executed at the end:
but if the cassandra package is already installed, this rm tasks is …

Prevent cassandra role to rm -rf its data in playbook reruns

---

ansible/doi-service-standalone.yml
ansible/roles/collectory/templates/config/collectory-config.properties
ansible/roles/doi-service/tasks/main.yml
ansible/roles/doi-service/templates/doi-service-config.yml

This PR, fix some missing space in DOI playbook that gives this error:
```
ERROR! Syntax Error while loading YAML.
found unexpected ':'
The error appears to be in '/home/vjrj/proyectos/gbif/dev/ala-install-up-to-date/ansible/doi-service-standalone.yml': line 9, column 68, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- {role: pg_instance, extensions: ["citext", "pgcrypto"]}
- {role: ansible-elasticsearch, es_version: 5.5.3, es_templates:false,  es_instance_name: 'doi-elasticsearch', es_data_dirs: ['/data/elasticsearch'], tags: ['elasticsearch']}
^ here
```
and also standardize the variables used por DB name/user/password. Also add a new variable `doi_service_port` to allow running it in a different port than `8080`.
Tested in …

DOI service vars fix and variables standardized

---

ansible/roles/collectory/templates/config/collectory-config.properties

I realized that `ala` layout is [more updated](https://github.com/AtlasOfLivingAustralia/ala-collectory/tree/master/grails-app/views/layouts) and collectory works better than with `generic` layout. 
This PR updates the default collectory skin layout and also creates a specific variable to configure it like other services (like `bie-hub`).
Also comments that `ala.skin` variable is [not in use now]( https://github.com/AtlasOfLivingAustralia/collectory-plugin/commit/f47c181ee4c5c52f150670f84f4f55f5d20ade31) so people (like me) don't lose time trying to figure out which value to use there. I don't remove it for backward compatibility.

Collectory layout variables updated

---

ansible/roles/bie-hub/tasks/main.yml
ansible/roles/biocache-hub/tasks/main.yml
ansible/roles/biocache-properties/tasks/main.yml
ansible/roles/collectory/tasks/main.yml
ansible/roles/dashboard/tasks/main.yml
ansible/roles/logger-service/tasks/main.yml
ansible/roles/regions/tasks/main.yml
ansible/roles/species-list/tasks/main.yml

In Guatemala deployment we notice that its organization name is not correctly encoded:
https://snib.conap.gob.gt/registros/#tab_simpleSearch
this is because `properties` should be encoded in `iso-8859-1` to allow use of non-latin characters, see
https://stackoverflow.com/questions/37436927/utf-8-encoding-of-application-properties-attributes-in-spring-boot
this doesn't happen with yml configs.
This patch add `output_encoding=iso-8859-1`  to the main ALA modules that still use `properties`  as config.
We didn't have this problem because, for instance, in Spain we use latin characters for our OrgName etc.
Tested with orgName in:
https://collections.l-a.site/
https://species.l-a.site/
Also related: https://github.com/AtlasOfLivingAustralia/ala-install/pull/381

Set output_encoding to iso-8859-1 for properties configs

---

ansible/roles/bie-index/templates/bie-index-config.yml
ansible/roles/image-service/templates/config/image-service-config.yml
ansible/roles/spatial-service/templates/spatial-service-config.yml
ansible/roles/species-list/templates/specieslist-webapp-config.properties
ansible/roles/userdetails/templates/userdetails-config.yml

Some roles don't have the skin.homeUrl in their config templates. 
Because of that the breadcrumbs **[Home](https://www.ala.org.au) >** links of these services points to www.ala.org.au. This patch add that variable to several roles to make this var also configurable (as other modules like [collectory do](https://github.com/AtlasOfLivingAustralia/ala-install/blob/cae407ac0c9173105f54c51da9e8265a27ef6bd1/ansible/roles/collectory/templates/config/collectory-config.properties#L72)).

Allow skin.homeUrl configuration in several roles

---

ansible/roles/alerts/templates/alerts-config.properties

This patch have relation with: 
https://github.com/AtlasOfLivingAustralia/alerts/pull/52
to allow to use the biocache-service url in alerts (instead of biocache-hub + hardcoded `/ws/`).
This role default value (and also of the `application.yml` in Alerts) should not affect to ALA alerts service.

Biocache service url instead of biocache-hub for alerts

---

ansible/roles/alerts/tasks/main.yml
ansible/roles/alerts/templates/alerts-config.properties
ansible/roles/regions/templates/regions-config.properties

I updated the alerts role with:
- CAS urls
- Missing skin typical variables
- properties encoding to `iso-8859-1` to allow use of non-latin characters in Alerts title sample variables (I think this should be the default is other roles still using properties, see the orgName in https://snib.conap.gob.gt/registros/#tab_simpleSearch)
https://stackoverflow.com/questions/37436927/utf-8-encoding-of-application-properties-attributes-in-spring-boot
- mysql default encoding to utf-8 (but configurable for backward compatibility) 
- Added `defaultResourceName` that is present in `application.yml`
Alerts samples with correct encoding:

Update of alerts properties (CAS, skin, mysql encoding, properties enc.)

---

ansible/roles/nginx_vhost/defaults/main.yml
ansible/roles/nginx_vhost/tasks/main.yml
ansible/roles/nginx_vhost/templates/ala_cors.j2
ansible/roles/nginx_vhost/templates/fragment_74_location_cors.j2

Following [this conversation in slack](https://atlaslivingaustralia.slack.com/archives/CCTFGEU1G/p1581527510131800) this fix #225.
Tested in a demo site.

Added CORS fragments to nginx_vhost role

---

ansible/roles/bie-hub/defaults/main.yml

Update of trove API url after deprecation of previous API. See: https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/196

Update trove API url

---

ansible/roles/nginx_vhost/tasks/main.yml

This is an attempt at a bug fix for issue #308 to try to support HTTP-only hosts that may have been HTTPS in the past and which cannot set `nginx_vhost_fragments_to_clear` to remove all old fragments on each ansible run.

issue #308 : Try to support HTTP-only hosts

---

ansible/roles/doi-service/templates/doi-service-config.yml

Continuing with https://github.com/AtlasOfLivingAustralia/doi-service/pull/55 that was merged recently, this PR adds the new DOI datacite varibles to the doi-service role.
I think also that this new pending PR should be reviewed with the new ansible variables: 
https://github.com/AtlasOfLivingAustralia/doi-service/pull/60
Tested in https://doi.gbif.es

New doi-service Datacite variables

---

ansible/roles/biocache-service/templates/config/download-doi-email.html
ansible/roles/biocache-service/templates/config/download-doi-readme.html
ansible/roles/biocache-service/templates/config/download-email.html
ansible/roles/biocache-service/templates/config/download-readme.html

We have a long-term strategy to support this and other similar www.ala.org.au URLs regardless of the way they are physically implemented. We are likely to move from Freshdesk to another system in the future at some point, and we want to preserve the ability to manage the citation link.
Reverts AtlasOfLivingAustralia/ala-install#415

The use of www.ala.org.au is intentional for long-term URL preservation

---

README.md

This ala-install repo is the main entrypoint for people interested in deploy a LA, but currently the README doesn't have references to some recent documentation and helper tools like the LA ansible generator.
Currently people try to deploy a LA portal starting from the vagrant inventories (see #419) or the demo playbook, but the effort necessary to go from these sample inventories to a production quality ones is enormous. Also we are testing more often these generated inventories that the demo and vagrant ones.
I suggest with this PR some changes in the README to try to help newcomers with links to the LA generator and LA Quick Start Guide.
I also changed the ubuntu version to 18, but we should change to 20 when it's more tested.
As these tools are not "oficial" tools developed by ALA, …

Improved README with links to the LA generator and LA Quick Start Guide

---

ansible/roles/spatial-service/tasks/main.yml

Spatial playbook fails because of a wrong location:
```
Sep 25 19:54:28 ala-install-test-3 nginx[20755]: nginx: [emerg] invalid URL prefix in /etc/nginx/sites-enabled/ala_default.conf:210
```
after this commit: https://github.com/AtlasOfLivingAustralia/ala-install/commit/60c6ddfc425a49a8bac5d42dea057d2ffb0acc4c
```
location /layers/more {
(...)
proxy_set_header X-Forwarded-Port $server_port;
proxy_read_timeout 10m;
proxy_pass /ws/layers/view/more;
```
I've tried to fix it adding the missing url.

Intent to fix for #395

---

ansible/image-service.yml

Added missing default values for postgres and postgis versions in image-service. This was causing this error:
```
TASK [postgresql : Gather OS Specific Variables] *******************************
fatal: [ala-install-test-2]: FAILED! => {"msg": "The conditional check 'ansible_os_family == \"RedHat\" or pg_version is not defined' failed. The error was: error while evaluating conditional (ansible_os_family == \"RedHat\" or pg_version is not defined): 'image_service_postgresql_version' is undefined\n\nThe error appears to be in '/data-additional/jenkins/ala-install-test/ala-install/ansible/roles/postgresql/tasks/old.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# tasks file for ntp\n- name: Gather OS …
```

Added default values for postgres version in image-service

---

ansible/aws-cas-5.yml

Added missing `appname` after: https://github.com/AtlasOfLivingAustralia/ala-install/commit/012d187c98bf56309946880cb7af82395a3abb76
```
fatal: [ala-install-test-1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'appname' is undefined\n\nThe error appears to be in '/data-additional/jenkins/ala-install-test/ala-install/ansible/roles/nginx_vhost/tasks/main.yml': line 100, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: set vfragments_suffix when vhost_with_appname_conf is true\n  ^ here\n"}
```
and later:
```
failed: [ala-install-test-1] (item={u'path': u'/cas', u'proxy_pass': u'http://127.0.0.1:9000/cas', u'is_proxy': True}) => {"ansible_loop_var": "item", …
```

Added missing appname in cas playbook

---

ansible/roles/nginx/tasks/setup-ubuntu.yml

Both in ubuntu 18.04 and 20.04 I get an error:
```
fatal: [ala-install-test-1]: FAILED! => {"changed": false, "msg": "Failed to find required executable gpg in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"}
```
during task " Add PPA key for Nginx repository".
I added `gpg` for these base ubuntu images that does not have gpg preinstalled.
Partially mentioned in #372.

Added gpg missing dependency in nginx role

---

ansible/roles/nginx/tasks/setup-ubuntu.yml

Reverts AtlasOfLivingAustralia/ala-install#430

Revert "Added gpg missing dependency in nginx role"

---

ansible/roles/nginx/tasks/setup-ubuntu.yml

I've rewritten #430 and I've tested in 16.04, 18.04 and 20.04 nginx role and species lists playbook. More details in: https://github.com/AtlasOfLivingAustralia/ala-install/pull/430#issuecomment-702634670 .
`gnupg` is present in all these ubuntu versions:
https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=gnupg
while `gpg` is not in `16.04`.

Added gnupg as nginx apt dep. Rewrite of #430

---

ansible/newserver.yml

Add a newserver ansible playbook to install both python2 and python3 on new servers.
This avoids forcing users to install python2 if they do not want it present on newer systems, and also avoids having to reinstall it in future instances.
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>

Add newserver ansible playbook to run once on new servers

---

ansible/roles/ansible-elasticsearch/tasks/elasticsearch-Debian.yml

Installing the `image-service` playbook alone in a VM I get:
```
TASK [ansible-elasticsearch : Debian - Add Elasticsearch repository key] *******
Tuesday 06 October 2020  16:45:48 +0200 (0:00:01.709)       0:00:47.266 ******* 
fatal: [ala-install-test-2]: FAILED! => {"changed": false, "msg": "Failed to find required executable gpg in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"}
```
so I patched following https://github.com/AtlasOfLivingAustralia/ala-install/pull/430#issuecomment-702634670 and #438 and the `image-service` playbook worked.
I used a plain .asc file instead of a keyring that probably required also the gpg package.

Fix missing gpg and deprecated apt-key for elasticsearch. #438

---

ansible/i18n.yml
ansible/roles/i18n/tasks/main.yml

A playbook just for install the `ala-i18n` deb package. I updated the `apt-get` part of the role.

Added i18n playbook and gpg dependency removed from role

---

ansible/roles/alerts/templates/alerts-config.properties
ansible/roles/apikey/templates/apikey-config.yml
ansible/roles/bie-index/templates/bie-index-config.yml
ansible/roles/biocache-hub/templates/config/config.properties
ansible/roles/collectory/templates/config/collectory-config.properties
ansible/roles/doi-service/templates/doi-service-config.yml
ansible/roles/image-service/templates/config/image-service-config.yml
ansible/roles/logger-service/templates/logger-config.properties
ansible/roles/regions/templates/regions-config.properties
ansible/roles/species-list/templates/specieslist-webapp-config.properties
ansible/roles/userdetails/templates/userdetails-config.yml

When several services are deployed in the same VM, the variable `skin_layout` are not set correctly for each different service.
For some reason we lost this commit https://github.com/AtlasOfLivingAustralia/ala-install/commit/7f2ede9f2ebfe1eacf7b6711b145f974659b2183 in the collectory configuration that address this problem partially.
But I also added similar variables to the rest of main services as I noticed that this was not working when mixing services in a VM.
This should not affect previous inventories (like the ALA inventories) that do not use these new variables and still use a basic `skin_layout` in each of their inventories.
The LA inventories generator it's ready to use these variables https://github.com/living-atlases/generator-living-atlas/commit/27724bf3062d41f2f21e2bd1fc8310ec …

Configurable skin layouts per services

---

ansible/biocache-service-clusterdb.yml

Testing in 18.04 and 20.04 I use the tomcat generic role with the tomcat version selected in facts.

Generic tomcat using common facts to choose correct one

---

ansible/roles/apikey/handlers/main.yml
ansible/roles/cas-management/handlers/main.yml
ansible/roles/cas5/handlers/main.yml
ansible/roles/doi-service/handlers/main.yml
ansible/roles/image-service/handlers/main.yml
ansible/roles/tomcat/handlers/main.yml
ansible/roles/userdetails/handlers/main.yml

Following https://stackoverflow.com/a/57677835 I added some extra var `skip_handlers` to allow prevent some handler to run (for instance if we want to update properties without restart a service).
This should not affect the current usage of `ala-install` and only skip the restart of some services when `-e skip_handlers=true` is added to `ansible-playbook`.

Added when to some handlers so can be skipped with -e skip_handlers=true

---

ansible/roles/doi-service/templates/doi-service-config.yml

Just adding `ala_base_url` to doi config template.

Add url to doi template

---

ansible/roles/doi-service/templates/doi-service-config.yml

Testing the doi service I noticed that datacite prefix variable in the config is parsed as float although [we try to read as String](https://github.com/AtlasOfLivingAustralia/doi-service/blob/fc753cfe4cdad465dcbd356153306a741aa86d87/grails-app/services/au/org/ala/doi/providers/DataCiteService.groovy#L28). In practice, some doi prefix like `10.1230` is read as `10.123`. I added some quotes in the config template to force its type to `String`.

Added quotes to doi prefix so it's parsed as String and not a Float

---

ansible/roles/collectory/templates/config/collectory-config.properties

I've exposed some variables from:
https://github.com/AtlasOfLivingAustralia/ala-collectory/blob/84aa9aace9c384c2d178321cdf24142db3ad30a1/grails-app/conf/Config.groovy#L110
Also I've added the `alerts_url` variable similar to the rest of roles trying not to affect to ALA inventories.

Added more download vars to collectory. Standardized alerts_url

---

ansible/aws-cas-5.yml
ansible/cas5-standalone.yml
ansible/roles/apikey/tasks/main.yml
ansible/roles/cas-management/tasks/main.yml
ansible/roles/cas5-dbs/tasks/main.yml
ansible/roles/cas5/tasks/main.yml
ansible/roles/mongodb-org/tasks/main.yml
ansible/roles/userdetails/tasks/main.yml

This PR do a refactorization of CAS playbooks and roles in order to:
- move tasks from playbooks to roles
- use of `roles` instead of `include_role` so we can use `--tags` properly with these playbooks
- maintain the same structure that the rest of playbooks and simplify the cas playbooks
This also solve: https://github.com/AtlasOfLivingAustralia/ala-install/issues/437
I've tested here (ubuntu `18.04` VMs):
https://auth-es.l-a.site/cas/login
https://auth-es.l-a.site/userdetails/
https://auth-es.l-a.site/apikey/
I'm working in this utility:
https://github.com/living-atlases/la-data-generator
that does not generate the properties for the `cas` services because of the current structure of the `cas` playbooks. So this also fix this `cas` properties generation (useful for LA based docker …

CAS playbooks and roles refactor

---

ansible/roles/cas5/tasks/main.yml
ansible/roles/cas5/templates/sql/admin-add.sql
ansible/roles/cas5/templates/sql/role-editor.sql

I'm trying to minimize the additional steps required to setup properly a new LA portal. 
https://github.com/AtlasOfLivingAustralia/documentation/wiki/LA-Quick-Start-Guide#post-install
Some of these are the `CAS` postinstall steps:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/CAS-postinstall-steps
and many other additional steps depends on these.
This optional task creates an admin user if some optional variables are present:
```
cas_first_admin_email=admin@example.com
cas_first_admin_bcrypt_password=$2a$10$PdZ9NacTV8GiqbTMzkd2bORXPmm2NobnCc387NVE6TEYwQacIznq.
cas_first_admin_temp_auth_key=7a07168e-1a5d-4924-83d2-bb06297348dc
```
It also creates the `ROLE_EDITOR` if not exists (some role that is used by some modules like the `collectory` but not present in new LA `CAS` …

First admin user creation as optional cas5 task for new LA deployments

---

ansible/roles/logger-service/tasks/main.yml
ansible/roles/logger-service/templates/sql/auth-ip.sql
ansible/roles/userdetails/tasks/main.yml
ansible/roles/userdetails/templates/sql/auth-ip.sql

Following #460 #461 and #462 and continue coding in ala-install current manual tasks, this PR adds IPs to the allow lists of `userdetails` and `logger`: 
https://github.com/AtlasOfLivingAustralia/documentation/wiki/Secure-your-LA-infrastructure#allowlist-ip-address
if some variables exists:
```
userdetails_authorize_ip_list=192.168.0.1, 192.168.0.2, 192.168.0.3
logger_authorize_ip_list=192.168.0.1, 192.168.0.2, 192.168.0.3
```
Some screenshots of the results:

Allow ip list insertion tasks in userdetails and logger

---

ansible/roles/apikey/tasks/main.yml
ansible/roles/bie-hub/tasks/main.yml
ansible/roles/biocache-hub/tasks/main.yml

Following the issue detected in https://github.com/AtlasOfLivingAustralia/ala-install/pull/461#issuecomment-772457759 I reordered the tasks in the apikey role.
I also include a service check that it's something that is also needed because in new installations the CAS services are not started.
https://github.com/AtlasOfLivingAustralia/documentation/wiki/CAS-postinstall-steps#restart-of-services-after-first-run
I'll send a PR with the same check for the rest of CAS services.
The result of this PR and the previous one that auto-creates the admin user:

Auto add apikeys from apikey role

---

ansible/roles/cas-management/tasks/main.yml
ansible/roles/cas5/tasks/main.yml
ansible/roles/userdetails/tasks/main.yml

Contining with conversation in https://github.com/AtlasOfLivingAustralia/ala-install/pull/462 these tasks ensure that CAS services are running at first install something that currently we do manually:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/CAS-postinstall-steps#restart-of-services-after-first-run
Some logs of these tasks:
```
TASK [Ensure cas is in a running state] ************************************************************************************************************************************************************************
Wednesday 03 February 2021  18:31:16 +0100 (0:00:00.086)       0:00:26.394 **** 
FAILED - RETRYING: Ensure cas is in a running state (15 retries left).
ok: [ala-install-test-1]
```

Ensure CAS services are running

---

ansible/roles/logger-service/templates/logger-config.properties

The last changes in logger config https://github.com/AtlasOfLivingAustralia/ala-install/commit/7ec553786938abd94147de96994a08ecb7f66508 https://github.com/AtlasOfLivingAustralia/ala-install/commit/7e1b6d62e229dc66554de447065b973d998ef661 breaks logger deploy on ubuntu 18.04. This PR add a condition in the config depending of the common mysql facts.

Logger mysql driver for mysql8 and others previous versions

---

ansible/roles/cas5-dbs/tasks/main.yml
ansible/roles/exec-jar/tasks/main.yml
ansible/roles/mongodb-org/tasks/main.yml
ansible/roles/mysql/tasks/main.yml
ansible/roles/postgresql/tasks/apt.yaml

This PR solve several errors when using python 3 and ansible like:
```
The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required.
```
or 
```
Failed to import the required Python library (psycopg2) on ala-install-test-2's Python /usr/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```
https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html

Install different deps if using ansible python 2 or 3

---

ansible/roles/common/tasks/setfacts.yml
ansible/roles/exec-jar/templates/service.conf
ansible/roles/java/tasks/openjdk-java-8.yml
ansible/roles/tomcat/tasks/main.yml
ansible/roles/userdetails/vars/main.yml

Fix for #481 following https://aws.amazon.com/blogs/opensource/tls-1-0-1-1-changes-in-openjdk-and-amazon-corretto/ first workaround option.
Maybe we should add this also for openjdk11 but I didn't have the opportunity to test it.

Fix for #481 enabling tls 1.0/1.1 for openjdk-8

---

ansible/roles/regions/templates/regions-config.properties

Small fix to allow a correct configuration of the home link using `skin.homeUrl` instead of `skin.homeURL` see:
https://github.com/AtlasOfLivingAustralia/ala-bootstrap3/blob/82ebda28f7cd53c81cdfe587894816dc6d2e373d/grails-app/views/layouts/_main.gsp#L80
Compare:
`grep -r skin.homeUrl ala-install`
with:
` grep -r skin.homeURL ala-install`

Correct skin.homeUrl instead of skin.homeURL in regions

---

ansible/ala-demo-basic.yml
ansible/newserver.yml
ansible/spatial.yml

This only adds a name to playbooks that use `all` as host group, so the ansible header logs are not very informative as they use `all` as header. This is useful for ansible logs post-processing.

Add play names to some playbooks

---

ansible/roles/java/templates/enableLegacyTLS.security

Added missing file in https://github.com/AtlasOfLivingAustralia/ala-install/pull/482 and https://github.com/AtlasOfLivingAustralia/ala-install/issues/481  sorry!
The difference:
``` 
< jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
---
> jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, \
```

Missing enableLegacyTLS.security

---

ansible/ala-demo-basic.yml
ansible/spatial.yml

Currently these two playbooks has `all` as `hosts`  so we have to use `--limit` everytime we use these playbooks. We use the respective host group for each playbook instead of  `all`.
These is useful for generated inventories with multiple hosts, services and groups in their inventories and should not affect to ALA spatial inventories (for instance).

Limit hosts in spatial and ala-demo playbook to respective groups

---

ansible/roles/exec-jar-generic/tasks/main.yml
ansible/roles/geoserver/tasks/geoserver.yml

This patch install `python-lxml` depending of the python version that ansible is using, preventing errors like:
```
TASK [geoserver : update defaultVectorCacheFormats in gwc-gs.xml for vectortiles extension] ***
Tuesday 25 May 2021  09:55:58 +0200 (0:00:06.383)       0:06:00.711 *********** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named lxml
fatal: [ala-install-test-3]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (lxml) on ala-install-test-3's Python /usr/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on …
```

Install lxml for python2 or python3 when necessary

---

ansible/roles/nameindex/tasks/main.yml

Probably the `nameindex` download tasks with the solr create cores task are the more annoying tasks in `ala-install` IMHO. The `nameindex` task because we have to skip it in order to not fill our disks with copies of the same downloaded nameindex on each playbook execution.
I patched this task to only backup an unarchive if the `nameindex` was downloaded.
Thanks to @cpfaff for the feedback.
In my tests only the task was needed in the last server, so in the first two ones the tasks are not executed:

Only download/untar nameindex when needed

---

ansible/roles/biocache-properties/tasks/main.yml

Although I tested #493 prior to send the PR and worked correctly:
```
TASK [biocache-properties : Extract SDS layers] *******************************************************************************************************************************************************************│··························
Wednesday 16 June 2021  17:14:04 +0200 (0:00:40.845)       0:00:49.664 ********                                                                                                                                    │··························
ok: [ala-install-test-1]
```
now I see that continues failing sometimes with the same error described in #493. So after reading [this/(https://github.com/ansible/ansible/issues/41877) I try with another extra option. 
Sorry for the noise...

Continuation of #493 as still fails sometimes

---

ansible/roles/mysql/tasks/main.yml

Fix for #495. After that, mysql root password is configured correctly:
```
TASK [mysql : warn about using the default root user password] *****************
Thursday 01 July 2021  16:15:42 +0200 (0:00:00.082)       0:01:37.818 ********* 
skipping: [ala-install-test-1]
TASK [mysql : change root user password on first run] **************************
Thursday 01 July 2021  16:15:43 +0200 (0:00:00.083)       0:01:37.902 ********* 
changed: [ala-install-test-1] => (item=ala-install-test-1)
changed: [ala-install-test-1] => (item=127.0.0.1)
changed: [ala-install-test-1] => (item=::1)
changed: [ala-install-test-1] => (item=localhost)
TASK [mysql : delete anonymous MySQL user for the host] ************************
Thursday 01 July 2021  16:15:45 +0200 (0:00:02.371)       0:01:40.273 ********* 
ok: …
```

Mysql root password configured correctly. Fix for #495

---

ansible/branding.yml
ansible/roles/branding/tasks/main.yml

This is a simplified version of the `ala-demo` role to just setup a vhost to deploy later a LA branding.
It's safe to merge it.

Basic branding role

---

ansible/roles/bie-hub/vars/main.yml
ansible/roles/biocache-hub/vars/main.yml
ansible/roles/regions/vars/main.yml

This PR just add some new optional artifact variables backwards compatible with old inventories.
These is used to deploy LA hubs but using the plain ala hub wars. For instance: 
```
biocache_hub = my-new-hub
biocache_hub_artifact = ala-hub
(...)
biocache_hub = my-other-hub
biocache_hub_artifact = ala-hub
```
will deploy `ala-hub.war` from nexus and setup the configuration of the hubs in `/data/my-new-hub` and `/data/my-other-hub`. So other LA portals can deploy several hubs easy (even in a shared server) without the need of building custom wars and using the typical `ala-install` playbooks (also without the need of creating playbooks for each hub).
This will used by a new functionality of the LA-Toolkit to deploy hubs:

Added optional artifact variables for hubs

---

ansible/pipelines.yml

My last changes in the pipelines playbook #503 exec `i18n` and `java` roles more than once. This simplifies again but using host groups instead of `all`.

Correct simplification of pipelines playbook

---

ansible/roles/pipelines_jenkins/tasks/main.yml

There was a small issue with the directory permissions of '.ssh' that make some task fails:
Also I reorder to mkdir `.ssh` before to add the key in slaves.

Fix for ssh key upload error in pipelines jenkins role

---

ansible/pipelines.yml
ansible/roles/i18n/tasks/main.yml
ansible/roles/la-apt/tasks/main.yml
ansible/roles/pipelines/defaults/main.yml
ansible/roles/pipelines/tasks/main.yml

This PR:
- adds `use_docker_with_pipelines` to optionally use docker with `pipelines`.
- creates a `la-apt` role to configure apt.gbif.es repository and include it in `pipelines` and `i18n` roles.
- when using the deb packages, adds new variables to setup them (for instance to use the gbif nameindex backbone).
It should not affect current ALA deployments as `use_docker_with_pipelines` is `true` by default.

Optional use of docker in pipelines vs direct deb packages

---

ansible/roles/collectory/templates/config/collectory-config.properties

Similar to other service, just adding some default value as https://github.com/AtlasOfLivingAustralia/ala-install/commit/27d62060935538f77b887ec4e1242ec0402566de fails on new deployments if this var is not defined:

Set default value for collectory auth_cookie_name

---

ansible/roles/pipelines/templates/la-pipelines-local.yaml

Just a simple PR to solve some copy/paste dup variables introduced by #520.

Fix copy/paste error in pipelines variables

---

ansible/roles/mongodb-org/tasks/main.yml

Prevent to use pymongo 4 for now. Fix for #525

---

ansible/roles/namedata/tasks/main.yml

I added some extra variables and tasks in `namedata` so we can use alternative namedatas in bie-index instead of the ALA combined default one. This was something we do manually until now. The `get_url` task also prevent to download the source if it was downloaded previously. Sample of usage:
```
namedata_to_use = custom
custom_namedata_repo = https://datos.gbif.es/namedata
custom_name_sources = "[ { 'name': 'gbif-backbone', 'checksum': 'sha256:6b753ff062337321df62377410bb728f90ae9e3e4e10f872639d1d6234b52ea5', 'datestamp': '2021-09-14' } ]"
```

Add custom namedata variables and tasks to use with GBIF Taxonomy and similars

---

ansible/roles/apikey/tasks/main.yml
ansible/roles/biocache-hub/files/data-quality-checks-with-pipelines.csv
ansible/roles/data_quality_filter_service/templates/config/config.properties

This PR:
- adds an additional `data_quality_skin_layout` variable.
- auto-add add the `data_quality` api key to apikey service if defined
- includes the `dataQualityChecksUrl` csv in ala-install files (instead of a google drive csv link) to use the raw csv github link. Or is ok if other LA portals use the ALA google drive link? I'm not sure of this part.

Minor improvements related to data-quality service

---

ansible/data_quality_filter_service.yml

I added an extra variable to allow to select a different `postgresql` version than the default one (13).  I tested it using pg 10 and it seems that works.
This allows us to use this service in other VMs with other services that are using pg 10 right now like the image-service.
Do you see any problem in using pg < 13 with the `data_quality_filter_service`?

data-quality postgresql version selectable

---

ansible/roles/ansible-elasticsearch/templates/jvm.options.j2
ansible/roles/common/tasks/setfacts.yml
ansible/roles/solr6/templates/solr.in.sh
ansible/roles/solr7/templates/solr.in.sh
ansible/roles/solrcloud/templates/solr.in.sh

Following: https://www.lunasec.io/docs/blog/log4j-zero-day/ 
although I'm not sure if the versions we are using of `log4j2` are vulnerable, I added the mitigation param for `tomcat,` `sorl,` `elasticsearch,` and `exec-jar` services `(cas,` `image-service,` `doi` ...).
Some screenshot after running this and restart services `(cas` services, `tomcat):`
`image-service`, `solr` and `elasticsearch:`

Trying to mitigate CVE-2021-44228

---

ansible/roles/bie-hub/tasks/main.yml

Using `iso-8859-1` in the `ala-bie-config.yml` configuration causes a startup exception in some cases:
```
2021-12-27 11:03:25.344 ERROR --- [.es-startStop-1] o.s.boot.SpringApplication               : Application startup failed
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
a8t org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200)
at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:146)
```
This is solved using an `utf-8` configuration that is supported by `yaml` ([in contrast to properties](https://github.com/AtlasOfLivingAustralia/ala-install/pull/382)).

Remove iso-8859-1 encoding in yaml config as support utf-8

---

ansible/roles/nameindex/tasks/main.yml

We link non ALA nameindexes similar as ALA does. This does not affect to ALA current use, so I'll commit.

Link non ALA nameindex too

---

ansible/roles/nameindex/tasks/main.yml

For non-ALA `nameindex`:
- Added more debug info
- Reorder of tasks
- added tags
- added checksum to `get_url`
I'll merge as not affects ALA.

Improve non-ala nameindex debug and added checksum

---

ansible/roles/la-apt/defaults/main.yml
ansible/roles/la-apt/tasks/main.yml

This allow to configure stable/unstable repo in apt.gbif.es so we can choose between tagged stable versions of packages and snapshot packages.
So you can select:
``` 
la_apt_repo = 'stable'
``` 
``` 
la_apt_repo = 'unstable'
``` 
Current content of stable:
`ala-senstive-data-service` is not there til we have a tagged version with the debian package.
We use a template now because if not several lines are added to the sources without replacing the previous one:
https://github.com/ansible/ansible/issues/58386#issuecomment-505888418

LA apt repos configurable

---

ansible/roles/collectory/templates/config/collectory-config.properties

Recently Tanzania team was unable to download datasets from GBIF because they used an email instead of an user id. Clarifying this in the template comments.

Added comments to collectory gbif properties

---

ansible/roles/bie-hub/tasks/main.yml

This fix the #539. Test with `/ws` `bie_index_context_path` (ALA use), the bie vhost with the bie-index redirect looks like :
Test with empty `bie_index_context_path` (used in several portals of the LA community) and without the redirect:
cc @biodivAtlasAT

Fix for #539

---

ansible/roles/collectory/templates/config/collectory-config.properties

In our production collectory using still `ala-collectory` suddenly we have `ala.org.au` urls:
This PR adds the previous `alert_url` used still by portals using `ala-collectory` as we need  https://github.com/AtlasOfLivingAustralia/collectory/issues/65 to migrate to `collectory`.
We setup also `userdetails` from the default value.

Added alert_url and userdetails to collectory config for backward compatibility

---

ansible/roles/branding/tasks/main.yml

This setup CORS for the branding of LA portals without the need of doing it manually.
I'll merge it as is something not used by ALA and I tested.

Added branding cors variable to setup cors in l-a branding only

---

ansible/roles/biocache-properties/templates/biocache-config.properties
ansible/roles/sds/tasks/main.yml

The `sds` configuration in `biocache-store` (sorry we are still there) still has some ALA default url values: 
https://github.com/AtlasOfLivingAustralia/sds/blob/b2b8157ecb8714e1a0175452a8ed1416572e3729/src/main/java/au/org/ala/sds/util/Configuration.java#L50
This PR configure these vars via ansible and also allow custom sds file configurations with inventories variables like:
```
sensitivity_zones_file = "{{ inventory_dir }}/files/custom-sensitivity-zones.xml"
```
It still has the ALA default values.

SDS extra configuration

---

ansible/roles/logger-service/defaults/main.yml

Set `logger_uri_filter_pattern` def value.
I have a doubt: It's this specific of logger >= 4.0.0 after the recent grails and deps update?

Correct logger auth filter

---

ansible/roles/collectory/templates/config/collectory-config.properties

New `is_pipelines_compatible` variable for https://github.com/AtlasOfLivingAustralia/collectory/pull/98.

Added isPipelineCompatible variable to collectory role

---

ansible/roles/collectory/templates/config/collectory-config.properties

This was generating incorrect Gbif url links in collectory:
https://www.gbif.org//publisher/797b2594-278e-421d-88c1-0925d122d611 (404)
Instead of:
https://www.gbif.org/publisher/797b2594-278e-421d-88c1-0925d122d611

Correct gbifWebsite url (without ending slash)

---

ansible/roles/pipelines/tasks/main.yml

Just some extra hdfs directories that should be created initially. To prevent this error, for instance during `clustering`:
> WARN : Putting block rdd_37_2 failed due to exception org.apache.beam.sdk.util.UserCodeException: org.apache.hadoop.security.AccessControlException: Permission denied: user=spark, access=WRITE, inode="/":hdfs:supergroup:drwxr-xr-xs

Extra hdfs directories

---

ansible/roles/spatial-hub/templates/spatial-hub-config.yml

Fix for #570. After this, spatial-hub does not throws the too-many-redirects error:
cc @biodivAtlasAT.

Fix for too-many-redirects error in spatial-hub

---

ansible/roles/solrcloud/tasks/main.yml

This PR import this pipeline initialization scripts and configs https://github.com/gbif/pipelines/tree/dev/livingatlas/solr/. 
Example of playbook run creating the `biocache` collection (the configset already exists) :
Run it again, the `biocache` collection already exists, so it doesn't do nothing:
I think should be safe to run in existing solrcloud deployments.

Create biocache configset and collection if not exists

---

ansible/roles/pipelines_jenkins/templates/jenkins/jobs/Ingest-dataset/config.xml.j2

With an initial ingest in a just installed cluster, the `uuid` step should be done after `interpretation`, if not:

Pipelines ingest job correct order

---

ansible/roles/pipelines/tasks/main.yml
ansible/roles/pipelines/templates/la-pipelines-local.yaml

This PR allows to configure the states provinces layer and also to add some extra layers (so we can reuse the political and ezz shapes from Australia). Sample conf:
```
geocode_state_province_layer = provincias
pipelines_shapefiles_extra_url = https://datos.gbif.es/others/layers/extra-layers.tgz
pipelines_shapefiles_extra_checksum = sha1:88b864096936416890cd4d01ec647d32b26b76ad
```

Pipelines extra shapes and state config

---

README.md

Some newcomers are trying to install a demo using vagrant a method that IMHO is not maintained and in use. I mark this method as deprecated and I add add a new howto that I just created showing how to use `microstack` and the `la-toolkit` to install a demo.

Add the microstack howto to the ala-install

---

ansible/roles/pipelines/tasks/main.yml
ansible/roles/pipelines/templates/la-pipelines-local.yaml

This PR includes:
- Some extra geocode variables to avoid the default values:
```
geocodeConfig:
country:
path: /data/pipelines-shp/political
field: ISO_A2
stateProvince:
path: /data/pipelines-shp/cw_state_poly
field: FEATURE
```
- Added download of vocabularies and configuration. 
- Customization of stateProvinces centroids

Additional pipelines geocodeConfig, vocabularies and location configuration

---

ansible/roles/geoserver/tasks/ecodata-geoserver.yml
ansible/roles/geoserver/tasks/geoserver.yml

Following https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956804 fix for task of #598 and #602.

Use of JAVA_OPTS instead of CATALINA_OPTS. Fix for #602

---

ansible/namematching-service.yml
ansible/roles/namematching-service/defaults/main.yml
ansible/roles/namematching-service/handlers/main.yml
ansible/roles/namematching-service/tasks/apt.yml
ansible/roles/namematching-service/tasks/main.yml
ansible/roles/namematching-service/templates/namematching-service-config.yml
ansible/roles/pipelines/tasks/main.yml
ansible/roles/sensitive-data-service/defaults/main.yml
ansible/roles/sensitive-data-service/handlers/main.yml
ansible/roles/sensitive-data-service/tasks/apt.yml
ansible/roles/sensitive-data-service/tasks/main.yml
ansible/roles/sensitive-data-service/templates/sensitive-data-service-config.yml
ansible/sensitive-data-service.yml

I proposed the debian package system as a way to avoid code duplication between people using ala-install based installations and these portals using docker.
But for instance `ala-sensitive-data-service` has now three ways to install the service:
1. the [docker image](https://github.com/AtlasOfLivingAustralia/ala-sensitive-data-service/blob/master/ala-sensitive-data-server/docker/Dockerfile) (using the deb package)
1. the [docker-test](https://github.com/AtlasOfLivingAustralia/ala-sensitive-data-service/blob/master/ala-sensitive-data-server/docker/Dockerfile-test) image (using a war instead of the debian package)
1. the `sensitive-data-service` role that installs the war via ansible instead of the debian package and that has tasks that the debian package already does (so we have duplicate …

Use of debian packages in namematching and sensitive service instead of war

---

ansible/data_quality_filter_service.yml
ansible/doi-service-standalone.yml
ansible/image-service.yml
ansible/phylolink.yml
ansible/roles/common/tasks/setfacts.yml
ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/tasks/debian.yml
ansible/roles/postgresql/tasks/postgis.yml
ansible/spatial.yml

Following my tests with #598 and #599 I moved the postgresql/postgis versions to common / set-facts.yml.
Also related with #597.

postgresql versions moved to common facts

---

ansible/roles/spatial-service/templates/spatial-service-config.yml

In this PR:
- I reenable logging (see https://atlaslivingaustralia.slack.com/archives/CCTFGEU1G/p1660658827331449)
- I allow to customize the `userdetails` urls

userdetails url configurable. Re-enable logging

---

ansible/roles/apikey/tasks/main.yml
ansible/roles/apikey/templates/apikey-config-pre-1.7.0.yml
ansible/roles/apikey/vars/main.yml
ansible/roles/cas-management/tasks/main.yml
ansible/roles/cas-management/templates/application.properties
ansible/roles/cas5/tasks/main.yml
ansible/roles/cas5/templates/application-pre-6.yml
ansible/roles/image-service/tasks/main.yml
ansible/roles/java/tasks/main.yml
ansible/roles/userdetails/tasks/main.yml
ansible/roles/userdetails/templates/userdetails-config-pre-3.yml
ansible/roles/userdetails/vars/main.yml

This PR allows to still install previous versions of CAS with ala-install. For that:
1. we require the install of java 11 (or 8) depending on each component version
1. we use previous ala-install (2.1.9) configurations of each cas components for that versions and new configurations for recent versions
1. we use jar of wars also depending of the version 
I'm not sure of this PR. I started to do point 1) and continued with the rest. Feel free to reject it.

CAS backwards compatibility with pre OIDC versions

---

ansible/roles/pipelines/templates/la-pipelines-local.yaml

Fix wrong  `sds_url` use in `la-pipelines-local.yml` template, so it was using incorrectly `https://sds.l-a.site` instead of the local senstivite-data-service.

Fix wrong sensitive-data-service url in pipelines

---

ansible/data_quality_filter_service.yml
ansible/doi-service-standalone.yml
ansible/image-service.yml
ansible/phylolink.yml
ansible/roles/common/tasks/setfacts.yml
ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/tasks/debian.yml
ansible/roles/postgresql/tasks/postgis.yml
ansible/spatial.yml

Reverts AtlasOfLivingAustralia/ala-install#600
This change forced installation of different postgres versions than were already installed and is not backwards compatible, needs to be reworked so postgres version isn't defined via set facts which has higher priority than basically everything else.

Revert "postgresql versions moved to common facts"

---

ansible/roles/pipelines/tasks/main.yml

Reviewing the `la-pipelines.yml` config, I think that this directories should be also created in hadoop. Please review it.

Added additional hdfs dirs

---

ansible/roles/userdetails/templates/userdetails-config.yml

Set default empty values (as other roles) to prevent:
```
TASK [copy userdetails-config.yml] *************************************************************************************
fatal: [gbif-es-auth-2022]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'userdetails_oidc_client_id' is undefined"}
```

Default userdetails values

---

ansible/data_quality_filter_service.yml
ansible/image-service.yml
ansible/phylolink.yml
ansible/roles/common/tasks/setfacts.yml
ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/tasks/debian.yml
ansible/roles/postgresql/tasks/postgis.yml
ansible/spatial.yml

I update the #600 reverted in #613. The difference is that now you can also set the `pg_version` and `postgis_version` if you use a different that the default ones:
PS: You'll need to update some of your inventories, for instance probably the `data_quality` inventory.

Rework of #600 now with pg and postgis version more configurable

---

ansible/roles/doi-service/vars/main.yml

PR to avoid errors like this one trying to install `doi-service` < `2.0`:
> TASK [exec-jar : Download doi-service JAR] *************************************
Thursday 15 September 2022  13:17:20 +0200 (0:00:00.742)       0:04:04.207 **** 
fatal: [ala-install-test-3]: FAILED! => {"changed": false, "msg": "Failed to download artifact au.org.ala:doi-service:war:exec:1.1.5 because of HTTP Error 404: Not Foundfor URL https://nexus.ala.org.au/content/groups/public/au/org/ala/doi-service/1.1.5/doi-service-1.1.5-exec.war"}

Conditional packaging war/jar in doi

---

ansible/roles/userdetails/templates/userdetails-config.yml

This PR externalize some variables to allow proper configuration of support and legal articles.
It also includes these variables (a PR not yet merged but quite safe):
https://github.com/AtlasOfLivingAustralia/userdetails/pull/135

Externalize some userdetails variables for non-ALA portals

---

ansible/roles/cas5-dbs/tasks/main.yml

This PR creates the mongo spring sessions db mentioned in: https://github.com/AtlasOfLivingAustralia/ala-cas-5/blob/develop/UPGRADE.MD and in this [slack thread](https://atlaslivingaustralia.slack.com/archives/CCTFGEU1G/p1662732769237899).
PS: Added to our [generated inventories too](https://github.com/living-atlases/generator-living-atlas/commit/0ece641f59710500166e4311ca75b772039a6f81).

CAS spring session db

---

ansible/roles/pipelines/files/log4j-spark.properties
ansible/roles/pipelines/files/logback.xml
ansible/roles/pipelines/tasks/main.yml

This PR allows to customize the la-pipelines `logback.xml` config and the spark `log4j` config. 
I used the `log4j.properties.template` provided by spark but using `WARN` as `log4j.rootCategory` as INFO was too verbose in recent versions of la-pipelines. See https://github.com/GBIFes/portal-datos-gbifes/issues/41

Allow to config logging in spark and la-pipelines

---

ansible/roles/collectory/templates/config/collectory-config.properties

With this PR we can configure some variables for other portals to avoid the default `ala.org.au` domain:

Allow configure some extra variables in collectory for non-ALA portals

---

ansible/roles/cas5/templates/application.yml

Externalize the logo variable ot the PR https://github.com/AtlasOfLivingAustralia/ala-cas-5/pull/30
With this others can easily set this logo:

Externalize cas logo image

---

ansible/roles/mysql/tasks/main.yml

Installing species lists in a new 20.04 VM, failed with this exception:
I fixed it, reordering the mysql tasks, so the sql-mode is set after the root password and `.my.cnf`are configured. 
I also added a missing register as in #496.

Mysql tasks reordered

---

ansible/roles/ecodata/templates/backup-ecodata.sh

Untested. just checking if I got the right idea
does `mongodump` create the dump directory? Wondering if that should be cleaned up after the backup is all tgziped up

automate ecodata daily/weekly/monthly backup management

---

ansible/roles/bie-hub/defaults/main.yml
ansible/roles/bie-hub/templates/bie-hub-config.yml.j2
ansible/roles/bie-index/templates/bie-index-config.yml

This PR externalize some extra url variables and then they can be configured by other LA portals (see ala.org.au variables):
Also allow to fine tune OIDC and related variables.

OIDC extra variables for bie. More configurable urls

---

ansible/roles/biocache-hub/templates/config/config.properties
ansible/roles/biocache3-properties/templates/biocache-config.properties

- Added new oidc related variables to `ala-hub` and `biocache-service` roles.
- Added extra named secret/clientId variables for LA portals with single inventories.

biocache oidc related variables

---

ansible/roles/data_quality_filter_service/templates/config/config.properties

- Added new oidc related variables to `dq-filter-service` role.
- Added extra named secret/clientId variables for LA portals with single inventories.
- Allow to enable/disable oidc for LA portals with not yet migrated auth systems
- Some extra API configuration variables

data-quality-filter-service oidc and other variables

---

ansible/roles/tomcat/tasks/main.yml

This is a fix of #641, adding the default options of debian instead of the variable `$JAVA_OPTS` only for ubuntu `18.04` when using `tomcat9`.

Fix for #641 and added debug

---

ansible/roles/image-service/templates/config/image-service-config.yml

I added a flag just similar to:
https://github.com/AtlasOfLivingAustralia/ala-install/pull/640/files
https://github.com/AtlasOfLivingAustralia/ala-install/pull/639/files

Allow to enable/disable oidc in image service

---

ansible/roles/biocache3-properties/templates/biocache-config.properties

This PR just adds the new variable introduced by https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/562 so it can be configurable.

Allow to show vernacular names optionally in biocache

---

ansible/roles/geoserver/tasks/geoserver.yml

This is a continuation of #656 with a task refactor in order to fix several things detected:
- tomcat and nginx are not started in the correct order so, tomcat is started without geoserver, but is not accesible externally.
- Fist geoserver start gives a `Found Java environment variable GEOSERVER_DATA_DIR set to /data/geoserver_data_dir , but this path does not exist` error.
For fix them, I reordered some tasks. I get other tasks (creation of datadir if not exists) present in the previous version of this geoserver tasks file.
Prior to this PR:
After running:

geoserver refactor of tasks

---

ansible/roles/geoserver/defaults/main.yml
ansible/roles/tomcat_deploy/tasks/main.yml

I added a option to optionally verify the checksum of a war download. 
This ensure the correct download of wars.
I added a example with the geoserver war. 
By default, in other wars should be work as before, without checking the checksum as the default value is ''.

Added optional checksum to war downloads with geoserver sample

---

ansible/roles/cassandra3/tasks/main.yml

Following https://cassandra.apache.org/_/download.html
Fix for #663.
I'll merge it so newcomers does not suffer this bug.

Use new debian repository of cassandra

---

ansible/roles/biocache-hub/handlers/main.yml
ansible/roles/biocache3-service/handlers/main.yml
ansible/roles/biocollect/handlers/main.yml
ansible/roles/biocollect/tasks/main.yml
ansible/roles/collectory/handlers/main.yml
ansible/roles/data_quality_filter_service/handlers/main.yml
ansible/roles/jenkins-simple/tasks/main.yml
ansible/roles/merit-grails4/handlers/main.yml
ansible/roles/mongodb-org/handlers/main.yml
ansible/roles/mongodb-org/tasks/main.yml
ansible/roles/namematching-service/handlers/main.yml
ansible/roles/namematching-service/tasks/apt.yml
ansible/roles/namematching-service/tasks/main.yml
ansible/roles/pipelines/tasks/main.yml
ansible/roles/profile-hub/tasks/main.yml
ansible/roles/profile-service/handlers/main.yml
ansible/roles/profile-service/tasks/main.yml
ansible/roles/sensitive-data-service/handlers/main.yml
ansible/roles/sensitive-data-service/tasks/apt.yml

Small adjustments to generate `/data` locally via https://github.com/living-atlases/la-data-generator.
It's add some new tags, some conditional service restart (to skip services to restart when we are looking only for configurations), and some minor fix (missing deps, new gpg key for jenkins).

Adjustments to generate /data locally

---

.gitignore
ansible/ecodata.yml
ansible/events.yml
ansible/roles/apikey/tasks/main.yml
ansible/roles/cas-management/tasks/main.yml
ansible/roles/cas5/tasks/main.yml
ansible/roles/doi-service/tasks/main.yml
ansible/roles/ecodata/handlers/main.yml
ansible/roles/ecodata/tasks/main.yml
ansible/roles/events/handlers/main.yml
ansible/roles/events/tasks/main.yaml
ansible/roles/geoserver/tasks/ecodata-geoserver.yml
ansible/roles/geoserver/tasks/geoserver.yml
ansible/roles/image-service/tasks/main.yml
ansible/roles/image-service/templates/config/image-service-config.yml
ansible/roles/pipelines/tasks/main.yml
ansible/roles/userdetails/tasks/main.yml
utils/ala-data-generator
utils/la-data-generator
utils/local.ini

This PR is a variant of the https://github.com/living-atlases/la-data-generator that generates the /data in a local machine. The idea is to generate configurations suitable for docker images.
Run with:
```
./ala-data-generator --inv=/home/youruser/ala/ansible-inventories/ --data=/data/docker generate doi
```
or for all services:
```
./ala-data-generator --inv=/home/youruser/ala/ansible-inventories/ --data=/data/docker generate
```
For la-toolkit generated inventories, use `./la-data-generator` instead. 
You can use `./utils/la-data-generator` too, and run it from other directories.
Some roles still need some adaptation and I trying to generate all the files with the $user of the user running the script. 
A sample of a db url for a `collectory-mysql` container:
```
$ grep mysql …
```

local /data config generation for docker use

---

utils/ala-data-generator
utils/la-data-generator
utils/local.ini

Just some extra options, continuing with #673:
-  to generate some single inventory:
```
./ala-data-generator --data=/data/docker ./collections-test
```
- Added extra-args for `solr_url` and similar portal specific variables:
```
/home/youruser/ala-install/utils/ala-data-generator --extra-args="solr_url=some_solr_host:2181" --data=/data/docker ./biocache-service-test-databox
```
- extra [groups] added to local.ini
- improved `-h`:
```
ala-data-generator: ALA data generator
Usage:
ala-data-generator [options] --data=<dir> --inv=<dir> generate [<service>...]
ala-data-generator [options] --data=<dir> <inventory>
ala-data-generator -h | --help
ala-data-generator -v | --version
Options:
--extra-args=<args>  Additional "arg1=values arg2=value" to get preference over defaul extra variables …
```

More local /data generation options

---

ansible/roles/bie-hub/tasks/main.yml
ansible/roles/bie-index/tasks/main.yml
ansible/roles/biocache-hub/tasks/main.yml
ansible/roles/biocache3-service/tasks/main.yml
ansible/roles/cas-management/tasks/main.yml
ansible/roles/cas5/tasks/main.yml
ansible/roles/cassandra3/tasks/main.yml
ansible/roles/collectory/tasks/main.yml
ansible/roles/namematching-service/tasks/main.yml
ansible/roles/sensitive-data-service/tasks/main.yml
ansible/roles/solrcloud/tasks/main.yml
ansible/roles/species-list/tasks/main.yml
ansible/roles/userdetails/tasks/main.yml

`include` is deprecated from ansible 2.4. It appears to behave like the new `import_*` (preprocessing) as opposed to the new `include_*` (runtime parsing).

change include to include_tasks

---

ansible/roles/biocache-cli/tasks/main.yml
ansible/roles/datacheck/tasks/main.yml
ansible/roles/datacheck/vars/main.yml
ansible/roles/pipelines_migration/tasks/main.yml
ansible/roles/tomcat_deploy/tasks/main.yml
ansible/roles/zoatrack/tasks/main.yml

In preparation for ALA's move from nexus 2 to nexus 3, all get_url calls to nexus are now done via the maven_artifact module.

nexus: replace get_url with maven_artifact

---

ansible/roles/nginx_vhost/templates/fragment_73_location.j2

Used by spring boot 2 to set server.tomcat.remoteip.host-header

nginx_vhost: add X-Forwarded-Host header for proxy

---

ansible/roles/solrcloud/tasks/docker-facts.yml
ansible/roles/solrcloud/tasks/docker-tasks.yml
ansible/roles/solrcloud/tasks/main.yml
ansible/roles/solrcloud_config/tasks/main.yml

As commented with @djtfmartin, in `solrcloud-config` role `bie` and `bie-offline` collections are not created, only `biocache`.
But in `solr` old roles all cores are created.
This PR add both `bie` collections if they don't exist (similarly to `biocache`).
I added some tags, and remove some `where` not necessary in docker-swarm deployment.

Create bie and bie-offline collection if not exists

---

ansible/auth-by-type.yml
ansible/bie-hub-by-type.yml
ansible/bie-index-by-type.yml
ansible/biocache-hub-by-type.yml
ansible/biocache-service-by-type.yml
ansible/biocache-service-clusterdb-by-type.yml
ansible/collectory-by-type.yml
ansible/image-service-by-type.yml
ansible/logger-service-by-type.yml
ansible/namematching-service-by-type.yml
ansible/namematching-service.yml
ansible/regions-by-type.yml
ansible/sensitive-data-service-by-type.yml
ansible/solrcloud-by-type.yml
ansible/spatial-by-type.yml
ansible/species-list-by-type.yml

I added some new playbooks to deploy on VMs or other deployments types based a `deployment_type` variable.
I'm not 100% happy with the solution as I prefer the something like "include" but for the moment it works. Maybe it can be improved in future ansible releases:
https://github.com/ansible/ansible/issues/34281
As this only add new playbooks it does not affect a previous uses.

Playbooks to deploy by-type

---

ansible/roles/datadog_apm/tasks/main.yml

For specieslists the actual service that runs is called tomcat9 but we still want to tag it as specieslists. This change lets us have separate values for the service tag namer and the actual service name
Not sure if lists is the only service where this occurs? Preference would be to change the specieslists service name from tomcat9 to specieslists
companion PR https://github.com/AtlasOfLivingAustralia/ansible-inventories/pull/52

separate variables for the service tag and the actual service name

---

ansible/roles/geonetwork/tasks/main.yml
ansible/roles/geonetwork/vars/main.yml
ansible/roles/geoserver/defaults/main.yml
ansible/roles/geoserver/vars/main.yml
ansible/roles/tomcat_deploy/tasks/main.yml

More work for #694, that works now as expected:
```
TASK [download from maven repo https://repo.osgeo.org/repository/release/org/geoserver/web/gs-web-app/2.19.2/gs-web-app-2.19.2.war] ***
Wednesday 11 October 2023  11:54:27 +0200 (0:00:00.472)       0:02:45.678 ***** 
changed: [ala-install-test-2]
```
Geonetwork it still failing because it's downloaded from a github release.

Geoserver and geonetwork fix for tomcat_deploy task

---

ansible/roles/nameindexer/tasks/main.yml
ansible/roles/nameindexer/vars/main.yml

Fix for #710 following the #690 work.
Tested:

Fix for 710

---

ansible/roles/pg_instance/tasks/main.yml

Fix for #712.
This does not fails now:

Fix for 712

---

ansible/roles/biocache-hub/tasks/main.yml
ansible/roles/biocache-hub/tasks/vm-tasks.yml

- biocache-hub role was running exec-jar for non-vm deployments when it is in vm-tasks. 
- It was also running exec-jar twice, with different configuration, for vm deployments.
- The most recent version of the duplicated code block was used.

fix biocache-hub merge

---

ansible/roles/profile-service/templates/profile-service-config.properties

Linked to https://github.com/AtlasOfLivingAustralia/profile-hub/issues/805

- fixed config to allow CORS requests from bie prod

---

ansible/roles/postgresql/tasks/apt.yaml

Fix for #727.
Testing logs in a `18.04` server:
```
TASK [postgresql : Add postgres archive repository] *********************************************************************************************************************************************************************************************************************************************************************************************************
ok: [ala-install-test-1]
TASK [postgresql : Add postgres repository] *****************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: …
```

Fix for 727

---

ansible/roles/regions/templates/regions-config.properties

I added the new regions map variables introduced by [this commit](https://github.com/AtlasOfLivingAustralia/ala-install/pull/new/regions-new-map-vars) to allow other LA Portals to configure their maps.

Added new regions map variables

---

ansible/roles/pg_instance/tasks/main.yml

Use shell instead of postgresql_ext to enable extensions

---

ansible/roles/bie-hub/templates/docker-compose.yml.j2
ansible/roles/bie-index/templates/docker-compose.yml.j2
ansible/roles/biocache-hub/templates/docker-compose.yml.j2
ansible/roles/biocache3-service/templates/docker-compose.yml.j2
ansible/roles/collectory/templates/docker-compose.yml.j2
ansible/roles/namematching-service/templates/docker-compose.yml.j2
ansible/roles/sensitive-data-service/templates/docker-compose.yml.j2
ansible/roles/species-list/templates/docker-compose.yml.j2
ansible/roles/userdetails/templates/docker-compose.yml.j2

Unpin docker versions to allow to use the same version variables as the VM tasks and use tags of 
https://hub.docker.com/u/atlasoflivingaustralia
For instance:
https://hub.docker.com/r/atlasoflivingaustralia/collectory/tags

Unpin docker versions

---

ansible/image-service.yml
ansible/roles/datadog_sql_user/tasks/main.yml
ansible/roles/exec-jar/tasks/main.yml
ansible/roles/exec-jar/templates/service.conf

- Add support for datadog jmx to exec jar roles
- Fix datadog sql role for non local database
- Remove using the CMS collector by default and replace with jvm extra params for clients if required

Updates for image service 3

---

ansible/roles/geoserver/defaults/main.yml
ansible/roles/geoserver/vars/main.yml

This tries to address #821 and continues with https://github.com/AtlasOfLivingAustralia/spatial-service/issues/224.
After running this:

Update geoserver to 2.25.2

---

ansible/newserver.yml

There is an indentation issue in `newserver.yml` that gives this error:
```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)
Syntax Error while loading YAML.
mapping values are not allowed in this context
The error appears to be in '/data-additional/jenkins/ala-install-test/ala-install/ansible/newserver.yml': line 9, column 10, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Get the distribution version
raw: lsb_release -r | awk '{print $2}'
^ here
```

Update newserver.yml indentation

---

ansible/biocache-service-clusterdb.yml

`tomcat10` should be used in `24.04`. Part of https://github.com/AtlasOfLivingAustralia/ala-install/issues/834

Update tomcat version in biocache-service-clusterdb.yml for u24.04

---

README.md
ansible/roles/userdetails/templates/sql/auth-ip.sql

When testing `ala-install` with ubuntu `20.04` (see #598) this error was raising:
```
TASK [userdetails : create auth ip in db if does not exists] *******************
Monday 29 April 2024  20:09:46 +0200 (0:00:01.300)       0:04:56.059 ********** 
(...)
ERROR 1267 (HY000) at line 2 in file: '/data/userdetails/setup/auth-ip.sql': Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='", "stderr_lines": ["mysql: [Warning] Using a password on the command line interface can be insecure
```
This PR fix this issue. 
This is the last issue I've detected testing Ubuntu `20.04`, so I modified the recommended version in the `README`.

Fix mysql collate error in ubuntu 20.04 and update README

---

ansible/roles/alerts/templates/alerts-config.properties

It seems that in https://github.com/AtlasOfLivingAustralia/ala-install/commit/6d6a59d9b8881a14b9621772690b3dbbebdcac75 a pipe is missing before `default` causing an error like:
```
TASK [alerts : copy all config.properties] *************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: . expected token 'end of print statement', got 'default'
fatal: [ala-install-test-1]: FAILED! => {"changed": false, "msg": "AnsibleError: template error while templating string: expected token 'end of print statement', got 'default'. String: # Grails config\nserverName={{ alerts_base_url }}\nserverURL={{ alerts_base_url }}\ngrails.serverURL={{ alerts_base_url }}{{ alerts_context_path }}\n\n# CAS Config\nsecurity.cas.appServerName={{ …
```

Update alerts-config.properties adding a missing pipe before default 

---

ansible/roles/postgresql/tasks/apt.yaml
ansible/roles/postgresql/vars/Ubuntu-24.04.yml

Part of #834.
This uses the 24.04 variables and skip to install the pip3 psycopg2 package as is installed with apt.
```
TASK [postgresql : Gather OS Specific Variables] *******************************
ok: [ala-install-test-2] => (item=/data-additional/jenkins/ala-install-test/ala-install/ansible/roles/postgresql/vars/../vars/Ubuntu-24.04.yml)
(...)
TASK [postgresql : install psycopg2] *******************************************
ok: [ala-install-test-2]
(...)
TASK [postgresql : pip3 psycopg2] **********************************************
skipping: [ala-install-test-2]
```

Fixes for postgresql in u24.04

---

ansible/doi-service-standalone.yml

Continuation of #834 removing the pg version from the doi playbook.

Remove hardcoded pg version from doi-service playbook

---

ansible/roles/nginx_vhost/tasks/main.yml
ansible/roles/nginx_vhost/templates/fragment_74_location_cors.j2

This allows to use  nginx confs generated by ansible outside the containers but it works too in traditional VM environments.
This was introduced by 9b58a27d6f2650d78ebdf83f28e763046167427a and lost in aacd03a1586a328f8291e20f77f796ab20b7e4ad  for some reason.

Revert relative symlink to sites-available for docker environments

---

ansible/roles/biocache-hub/templates/config/config.properties
ansible/roles/biocache3-properties/templates/biocache-config.properties

Just adding this variable that was introduced by https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/562 but added incorrectly to the `biocache-service` config.

Moved vernacularName.show to ala-hub

---

ansible/roles/nginx_vhost/templates/fragment_74_location_cors.j2

I introduced a bug today in `nginx_vhost` that I didn't test in all the environments (in the last commit of #807). I restore the previous line with an option for docker swarm environments.
I've just tested and works as before in a normal vm environment.
Sorry.

Fix for wrong cors include

---

ansible/spatial.yml

This PR re-adds the `i18n` role to the spatial playbook that was commented. In order to disable a:
```
i18n_package_enabled=False
```
can be added to the inventories (although the i18n contains the up-to-date version of English so was implemented trying to not affect ALA or other English portals).

Re-add i18n role to spatial

---

ansible/roles/alerts/templates/alerts-config.properties
ansible/roles/bie-hub/templates/bie-hub-config.yml.j2
ansible/roles/bie-index/templates/bie-index-config.yml
ansible/roles/dashboard/templates/dashboard-config.properties
ansible/roles/doi-service/templates/doi-service-config.yml
ansible/roles/logger-service/templates/logger-config.properties
ansible/roles/species-list/templates/specieslist-webapp-config.properties

Only some additional variables useful for the LA community using a single inventory for deploy all its services. It defaults to the ALA current variables/values so should not affect to ALA.
For instance, I detected some urls via `/alaAdmin/viewConfig` pointing to `ala.au.org` ones.

New variables for the LA community

---

ansible/roles/bie-hub/templates/blacklist.json.j2

This fix #856 and also allow to setup the country in the metadata.
This allows to use wikipedia by new portals without configuring initially a `blacklist_source`.

Correct empty bie blacklist when blacklist_source is not defined

---

ansible/cassandra5.yml
ansible/roles/cassandra5/defaults/main.yml
ansible/roles/cassandra5/files/conf/90-nproc.conf
ansible/roles/cassandra5/files/conf/limits.conf
ansible/roles/cassandra5/files/yum/datastax.repo
ansible/roles/cassandra5/handlers/main.yml
ansible/roles/cassandra5/tasks/main.yml
ansible/roles/cassandra5/tasks/vm-tasks.yml
ansible/roles/cassandra5/templates/cassandra-env.sh
ansible/roles/cassandra5/templates/cassandra.yaml
ansible/roles/cassandra5/vars/main.yml
ansible/roles/common/tasks/main.yml

Constructed using the cassandra3 role as a base, then determining what changed in the cassandra3 templates from the defaults, and finally applying these same changes to the cassandra5 defaults.

#834 add cassandra5 for vm

---

ansible/roles/common/defaults/main.yml

This pull request includes a small change to the `ansible/roles/common/defaults/main.yml` file. The change adds a new configuration option for `use_openjdk17` to avoid errors like #854 and with a similar use than for older versions.

Add option for OpenJDK 17 in defaults

---

ansible/roles/zookeeper/templates/zoo.cfg.j2

Change for solr 8.2+ to allow solr admin to query zookeeper for health status etc

zookeeper: add whitelist for recent solr

---

ansible/roles/common/tasks/setfacts.yml

Currently, services like `images` fails to install postgis extensions with the error:
```
TASK [postgresql : run the postgis SQL scripts] ********************************
failed: [ala-install-test-1] (item=/usr/share/postgresql/14/contrib/postgis-3.4/postgis.sql) => {"ansible_loop_var": "item", "changed": true, "cmd": ["psql", "-d", "postgis_template", "-f", "/usr/share/postgresql/14/contrib/postgis-3.4/postgis.sql"], "delta": "0:00:00.020077", "end": "2025-06-20 07:53:04.403125", "item": "/usr/share/postgresql/14/contrib/postgis-3.4/postgis.sql", "msg": "non-zero return code", "rc": 1, "start": "2025-06-20 07:53:04.383048", "stderr": "psql: error: /usr/share/postgresql/14/contrib/postgis-3.4/postgis.sql: No such file or directory", "stderr_lines": ["psql: error: …
```

Fix postgis version for u22 (see #599)

---

ansible/roles/solr/defaults/main.yml
ansible/roles/solr/tasks/main.yml
ansible/roles/solr/templates/solr.in.sh.solr7
ansible/roles/solr/templates/solr.in.sh.solr8
ansible/roles/solr/vars/main.yml
ansible/roles/solr7/templates/solr.in.sh
ansible/solr-standalone.yml

This pull request introduces a generic `solr` role that include the addition of version-specific configuration templates and dependencies.
You can select the version to install with `solr_version`.
The role is quite similar to `solr7` and `solr6` ones…
Also change the `ansible/roles/solr7/templates/solr.in.sh` similarly to allow running `solr7`  with `openjdk` > 8 as currently it fails with unsupported options like:
https://issues.apache.org/jira/browse/SOLR-10184

Generic solr role

---

ansible/roles/exec-jar/defaults/main.yml
ansible/roles/exec-jar/templates/service.conf

Adds a default HTTP User Agent via the Java http.agent system property

Add default HTTP user agents
