ansible/inventories/vagrant/layers-service-vagrant
ansible/roles/common/tasks/main.yml
ansible/roles/geoserver/templates/geoserver.distributions.xml
ansible/roles/geoserver/templates/geoserver.objects.xml
ansible/roles/postgresql/tasks/main.yml
ansible/roles/solr/files/solr/bie/conf/schema.xml
ansible/roles/tomcat/tasks/main.yml

various fixes for geoserver installation and layer setup

various fixes for geoserver installation

---

README.md

Add instructions for installing virtual box and vagrant-1.7 on ubuntu.

Readme for installing virtual box and vagrant on ubuntu

---

README.md
ansible/inventories/vagrant/demo-vagrant
ansible/roles/demo/templates/index.html
vagrant/ubuntu-xenial/Vagrantfile

**Reason:** The official repository only worked with me with these settings.
**Note:** I am performing the installation on a new partition with Ubuntu 16.0.4.

Fix ala-install

---

ansible/roles/bie-index/templates/bie-index-config.properties
ansible/roles/solr/files/solr/bie/conf/schema.xml
ansible/roles/solrcloud_config/files/bie-offline/conf/schema.xml
ansible/roles/solrcloud_config/files/bie/conf/schema.xml

Make taxonRemarks multivalued and add provenance field to the bie solr schemas

Additional BIE fields

---

ansible/roles/logger-service/files/db/update_breakdown_summary_information.sql

Fix for #211

---

ansible/bie-test.yml
ansible/roles/bie-index/tasks/main.yml
ansible/roles/bie-index/templates/bie-index-config.yml
ansible/roles/solrcloud_config/files/bie-offline/conf/schema.xml
ansible/roles/solrcloud_config/files/bie-offline/conf/solrconfig.xml
ansible/roles/solrcloud_config/files/bie/conf/schema.xml
ansible/roles/solrcloud_config/files/bie/conf/solrconfig.xml

Update BIE schemas and solr configuration for latest BIE.
* Updated solr to 6.6.5
* Updated solr schemas for bie
* The bie configuration is now a .yml file

Updated BIE configuration

---

ansible/roles/bie-index/templates/bie-index-config.yml

Also explicitly set boost field

Include exact_text in query fields for BIE

---

ansible/image-service.yml

Minor fix including db vars after last playbook update, cc @djtfmartin

Fix vars in images playbook

---

ansible/roles/mongodb-org/defaults/main.yml
ansible/roles/mongodb-org/handlers/main.yml
ansible/roles/mongodb-org/tasks/main.yml
ansible/roles/mongodb-org/templates/mongod.yml

Some basic mongodb.org package role with admin user creation and authentication.

Added basic mongodb.org role for using with CAS-5

---

ansible/roles/bie-index/templates/bie-index-config.yml

Just setting a pair of two new default vars.

Setting a pair of def vars

---

ansible/roles/collectory/templates/config/collectory-config.properties

Added `ws/ipt/scan` to `uriFilterPattern` allowing to update `ipt` providers when using CAS in `collectory`.

Added collectory uriFilterPattern allowing to update ipt providers when using CAS

---

ansible/inventories/living-atlas-cas-5

I updated the demo CAS playbook to use the last CAS versions, thanks to @sbearcsiro

Updated CAS versions to follow ALA production versions

---

ansible/roles/spatial-hub/templates/spatial-hub-config.yml

Following this PR https://github.com/AtlasOfLivingAustralia/spatial-hub/pull/255 I allow to set some extra vars to spatial-hub

Added apikey and lang to spatial-hub config template

---

ansible/roles/geoserver/tasks/main.yml

Just some additional tags to allow proper skipping or selection of all the geoserver tasks.

Added additional tags to geoserver to match all the tasks

---

ansible/ala-demo.yml
ansible/inventories/living-atlas
ansible/inventories/living-atlas-spatial

I updated a little bit the LA inventories and added also the spatial one (using the generator and the Paris workshop inventories as reference).
Related with:
https://github.com/AtlasOfLivingAustralia/ala-install/issues/356

Living altas demo inventories updated. Added spatial inventory

---

ansible/roles/species-list/templates/specieslist-webapp-config.properties

Added `orgNameShort` variable for https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/148

Added orgNameShort to speciesLists

---

ansible/roles/doi-service/templates/doi-service-config.yml

Just adding some reconnection params and codification to the db url (the db is already created with utf-8 encoding)

Added reconnection params to doi db url

---

ansible/roles/i18n/tasks/main.yml

I installed this apt repository in a dedicated VM in a more reliable environment.

Switch to apt.gbif.es ala-i18n repo

---

ansible/roles/biocache-service/templates/config/download-doi-email.html
ansible/roles/biocache-service/templates/config/download-doi-readme.html
ansible/roles/biocache-service/templates/config/download-email.html
ansible/roles/biocache-service/templates/config/download-readme.html

As requested in https://github.com/AtlasOfLivingAustralia/DataQuality/issues/129

updated cite-ala url

---

ansible/inventories/vagrant/biocache-backend-vagrant
ansible/inventories/vagrant/demo-vagrant
ansible/inventories/vagrant/doi-service-vagrant
ansible/inventories/vagrant/merit-vagrant
ansible/inventories/vagrant/pdf-service-vagrant
ansible/inventories/vagrant/phylolink-vagrant
ansible/inventories/vagrant/regions-vagrant
ansible/inventories/vagrant/spatial
ansible/inventories/vagrant/spatial-vagrant
ansible/inventories/vagrant/species-list-vagrant

I added missing nginx_vhost_fragments_to_clear in some vagrant inventories.

Added missing var in some vagrant inventories. Fix for #419

---

ansible/roles/regions/files/state-emblems.json

I updated the guids of state-emblems.json in a similar way to AtlasOfLivingAustralia/regions#78

Updated guids of state-emblems.json 

---

ansible/roles/collectory/templates/config/collectory-config.properties

I minor change to enable 'alaAdmin' interface by default in collectory.

Enable alaAdmin in collectory uriFilterPattern

---

README.md

I just added a statement about currently tested distros and ansible use to help to newcomers. Feel free to rewrite it.

Added distros to README and some ansible tip for newbies

---

ansible/namematching-service.yml
ansible/roles/exec-jar-generic/defaults/main.yml
ansible/roles/exec-jar-generic/tasks/main.yml
ansible/roles/exec-jar-generic/templates/log4j.xml
ansible/roles/exec-jar-generic/templates/logback.xml
ansible/roles/exec-jar-generic/templates/systemd.service
ansible/roles/exec-jar-generic/templates/wrapper
ansible/roles/nameindex/tasks/main.yml
ansible/roles/namematching-service/defaults/main.yml
ansible/roles/namematching-service/files/groups.json
ansible/roles/namematching-service/files/subgroups.json
ansible/roles/namematching-service/handlers/main.yml
ansible/roles/namematching-service/tasks/main.yml
ansible/roles/namematching-service/templates/namematching-service-config.yml
ansible/roles/namematching-service/vars/main.yml
ansible/roles/sds/files/sensitivity-categories.xml

Namematching-service install
Plus some extra categories for SDS

Namematching service

---

ansible/roles/alerts/templates/alerts-config.properties

Following PR https://github.com/AtlasOfLivingAustralia/alerts/pull/55 I just add a pair of these new vars:
https://github.com/AtlasOfLivingAustralia/alerts/blob/02c3cf8975f9e8a1408b5b7e27941aa0322e15b3/grails-app/conf/application.yml#L109

Added new alerts variables

---

ansible/roles/spatial-hub/tasks/main.yml
ansible/roles/spatial-service/tasks/main.yml

I just added some `properties` tags to the `spatial-hub` and `spatial-service` roles.

Added properties tag to spatial roles

---

ansible/roles/bie-index/tasks/main.yml
ansible/roles/biocache-service/tasks/main.yml
ansible/roles/geoserver/tasks/geoserver.yml
ansible/roles/image-service/tasks/main.yml
ansible/roles/logger-client/tasks/main.yml
ansible/roles/solr7/tasks/main.yml

I've been just adding some more properties tags in different roles.

Added some more properties tags

---

ansible/roles/demo/tasks/main.yml

I just added some tags and variable to /etc/hosts task in demo role.
Tested in a demo. I directly merge it.

Add condition to /etc/hosts conf task in demo role

---

ansible/roles/biocache-properties/templates/biocache-config.properties

Just removing some spaces in DOI urls of biocache-service

Removed spaces in DOI urls

---

ansible/roles/bie-index/templates/bie-index-config.properties
ansible/roles/bie-index/templates/bie-index-config.yml

Add a section to bie-index config with knowledgebase configuration params to provide for site-specific KB content.
Add a inventory variable to set the knowlegebase service url.

Add configuration content and vars for knowledgebase service

---

ansible/roles/regions/templates/regions-config.properties

Added new variable to use https://github.com/AtlasOfLivingAustralia/regions/pull/86. Tested in our production service.

Added new regions variable

---

ansible/roles/biocache-hub/templates/config/config.properties

added a new config dataquality.warningOn to indicate if to display the data quality warning dialog

added a new config dataquality.warningOn

---

ansible/spatial.yml

Fix typo introduced by #475

---

ansible/roles/ansible-elasticsearch/defaults/main.yml
ansible/roles/bie-hub/defaults/main.yml
ansible/roles/sds/templates/sds-config.properties

Fix for #490 and #480. Added some [sds variable](https://github.com/AtlasOfLivingAustralia/sds-webapp2/blob/4b997f3a4db963116c01e6a59077e63db4db44a6/grails-app/conf/application.yml#L113).

Several missed & new vars: Fix for #490 and #480. Added new sds var.

---

ansible/roles/solrcloud/defaults/main.yml
ansible/roles/solrcloud/tasks/main.yml

Feature solr8 merge

---

ansible/roles/pipelines/tasks/main.yml
ansible/roles/pipelines/templates/la-pipelines-local.yaml

I added some more ansible variables to the local la-pipelines config. I used the values from the:
https://github.com/gbif/pipelines/blob/dev/livingatlas/configs/la-pipelines.yaml
trying to not affect the ALA current inventories.
I added a pair or tags also to continue using the `properties` tag as with other roles.

Added ansible variables to la-pipelines config

---

ansible/roles/apikey/tasks/main.yml
ansible/roles/cas-management/tasks/main.yml
ansible/roles/cas5/tasks/main.yml
ansible/roles/doi-service/tasks/main.yml
ansible/roles/exec-jar/tasks/main.yml
ansible/roles/java/tasks/openjdk-java-8.yml
ansible/roles/tomcat/tasks/main.yml
ansible/roles/userdetails/tasks/main.yml

Just some extra tags to easy apply #530 . I'll merge directly

Extra tags to easy apply log4j2 exploit mitigation related tasks

---

ansible/roles/collectory/templates/config/collectory-config.properties

Correct gbif api url in collectory

---

ansible/roles/tomcat/tasks/main.yml

Rename tomcat config task as not only set the memory

---

ansible/roles/biocache-hub/templates/config/config.properties

Added missing supportEmail. Fix for #551

---

ansible/roles/pipelines/tasks/main.yml

- I added new debian variables following https://github.com/AtlasOfLivingAustralia/ala-sensitive-data-service/pull/13 
- some new ansible tags
- layers configurable and with checksum for faster runs
Tested in our testing environment.

New ala-sensitive-data-service vars, more tags, and layers vars

---

ansible/data_quality_filter_service.yml

Fix for #549. Without it, we had this weird errors:
and now install correctly:

Fix for #549

---

ansible/roles/collectory/templates/config/collectory-config.properties

A simple conditional to choose the filters to apply depending on the `collectory_version` to fix #554.

Fix for #554

---

ansible/roles/data_quality_filter_service/templates/config/config.properties

These patterns are handled by the app and shouldn't be overridden

Remove filter patterns from data_quality_filter_service

---

ansible/roles/pipelines_jenkins/tasks/main.yml

Just an additional flag to not update or not the pipelines jenkins jobs (to maintain custom modifications).

Update jenkins jobs optionally

---

ansible/roles/pipelines_jenkins/tasks/main.yml

Create jenkins job directories

---

ansible/roles/pipelines_jenkins/templates/jenkins/jobs/Export-Cassandra-to-DwCA/config.xml.j2

Fix for #582 , thanks @djtfmartin . I've just added `{{master_node}}` as assigned jenkins node.

Added Export-Cassandra-to-DwCA job

---

ansible/roles/pipelines_jenkins/templates/jenkins/jobs/Copy-DwCA/config.xml.j2
ansible/roles/pipelines_jenkins/templates/jenkins/jobs/Delete-dwca-from-hdfs/config.xml.j2

Basically:
- Download/copy: `sudo -u spark la-pipelines copy someDrIds --hdfs`
- Delete: `sudo -u spark /data/hadoop/bin/hdfs dfs -rm -r -f /dwca-exports/someDr`

Added two pipelines jobs to copy/delete specific drs to hdfs

---

ansible/roles/postgresql/vars/Ubuntu-22.04.yml
ansible/roles/volunteer-portal/tasks/main.yml

Fix tasks in the volunteer-portal (Digivol) role, and add Ubuntu 22 support in the postgresql role.

Volunteer portal fixes 2022 06

---

ansible/roles/la-apt/tasks/main.yml

I simple debug task for the apt repository.

Added apt debug task

---

ansible/biocache-db.yml
ansible/pipelines.yml
ansible/roles/image-service/vars/main.yml

Fix for 608

---

ansible/roles/pipelines_jenkins/tasks/main.yml
ansible/roles/pipelines_jenkins/templates/jenkins/jobs/Migrate-uuid/config.xml.j2

Just install the migration.jar via apt.

Added la-pipelines-migration dependency for Migration-uuid job

---

ansible/roles/bie-hub/tasks/main.yml
ansible/roles/bie-index/files/vernacular-lists.json
ansible/roles/sensitive-data-service/templates/sensitive-data-service-config.yml

Also:
Remove IEK lists which are in combined taxonomy
Add tag to allow easy BIE block list updates

Remove date clear in sensitive data web service

---

ansible/roles/collectory/templates/config/collectory-config.properties
ansible/roles/logger-service/templates/logger-config.properties
ansible/roles/species-list/templates/specieslist-webapp-config.properties

I added more OIDC related variables, I normalized some variables to enable/disable it and to allow configure non ALA urls.

More OIDC related variables

---

ansible/roles/biocache-properties/templates/biocache-config.properties
ansible/roles/biocache3-properties/templates/biocache-config.properties

Changes to biocache-service template  for OIDC and Java 11, gradle and spring upgrades

Feature/biocache OIDC auth

---

ansible/roles/pipelines_jenkins/templates/jenkins/jobs/Delete-dwca-from-hdfs/config.xml.j2

Following this thread:
https://atlaslivingaustralia.slack.com/archives/CCTFGEU1G/p1669889592683779
this PR improves the pipelines delete dwca job.

Added extra commands to delete job in pipelines jenkins

---

ansible/roles/collectory/templates/config/collectory-config.properties

Simple path fix for gbif license location.
I'll directly merge it.

Fix for license default location

---

ansible/roles/regions/templates/regions-config.properties

Just some variables to enable/disable oidc and cas similar to other modules.

Allow disable/enable of oidc/cas in regions

---

ansible/roles/cas5-dbs/tasks/main.yml

Added extra tag to mongo cas dbs

---

ansible/roles/cas5-dbs/tasks/main.yml

Removing extra spaces during the commit I removed also a colon.  Fixing it.

Fix missing colon

---

ansible/roles/geoserver/defaults/main.yml
ansible/roles/tomcat_deploy/tasks/main.yml

This PR tries to fix #694 with a fallback.

Trying to fix 694

---

ansible/roles/species-list/files/v4.4.0_update.sql

SQL scripts to create / update tables

lists 4.4.0 database update

---

ansible/roles/bie-hub/tasks/main.yml
ansible/roles/bie-index/tasks/main.yml
ansible/roles/biocache-hub/tasks/main.yml
ansible/roles/biocache3-service/tasks/main.yml
ansible/roles/cas-management/tasks/main.yml
ansible/roles/cas5/tasks/main.yml
ansible/roles/cassandra3/tasks/main.yml
ansible/roles/collectory/tasks/main.yml
ansible/roles/namematching-service/tasks/main.yml
ansible/roles/sensitive-data-service/tasks/main.yml
ansible/roles/solrcloud/tasks/main.yml
ansible/roles/species-list/tasks/main.yml
ansible/roles/userdetails/tasks/main.yml

Import vm tasks

---

ansible/image-service-by-type.yml
ansible/logger-service-by-type.yml
ansible/regions-by-type.yml
ansible/spatial-by-type.yml

I cherry-pick a commit from #697 as is affecting the current use of ala-install:

Comment not (yet) existing docker roles

---

ansible/roles/species-list/files/v4.4.0_update.sql
ansible/roles/species-list/templates/specieslist-webapp-config.properties

4.5.0 security plugin update
#https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/287 lists 4.4.0 database update

4.5.0 lists-test security plugin update

---

ansible/roles/ecodata/templates/ecodata-config.properties
ansible/roles/ecodata/templates/runMuDownload.sh

- added ecodata instance to ip white list

- fixed management unit report

---

ansible/roles/collectory/templates/config/collectory-config.properties

Adding a default value so as not to break anything.

add collectory config gbifDefaultEntityCountry

---

ansible/roles/tomcat/templates/systemd-service-override.conf.j2

Related to https://github.com/AtlasOfLivingAustralia/ala-install/pull/755
For services that use tomcat to run, have them restart on failure also. 
eg. alerts, lists, spatial, collections

have tomcat restart on failure

---

ansible/roles/fieldguide/templates/fieldguide-config.yml
ansible/roles/image-service/templates/config/image-service-config.yml

Fix config

---

ansible/roles/bie-hub/templates/bie-hub-config.yml.j2
ansible/roles/bie-index/templates/bie-index-config.yml
ansible/roles/biocache3-properties/templates/biocache-config.properties
ansible/roles/spatial-hub/templates/default/spatial-hub-config.yml
ansible/roles/spatial-service/templates/spatial-service-config.yml
ansible/roles/userdetails/templates/userdetails-config.yml

Looking for another set of eyes to check syntax of if statements, for copy and paste mistakes, etc.

Add config to support new species-lists

---

ansible/bie-hub-docker.yml
ansible/docker-swarm.yml
ansible/image-service-by-type.yml
ansible/logger-service-by-type.yml
ansible/regions-by-type.yml
ansible/roles/bie-hub/tasks/main.yml
ansible/roles/bie-hub/templates/docker-compose.yml.j2
ansible/roles/bie-index/defaults/main.yml
ansible/roles/biocache3-properties/templates/biocache-config.properties
ansible/roles/biocache3-service/tasks/main.yml
ansible/roles/cassandra3/tasks/docker-tasks.yml
ansible/roles/solrcloud/tasks/main.yml
ansible/roles/solrcloud/templates/docker-compose.yml.j2
ansible/spatial-by-type.yml

This PR includes improvements to the docker swam deployments and does not affect to current VM deployment or ALA.

More work in docker swarm deployments

---

ansible/roles/image-service/templates/config/image-service-config.yml
ansible/roles/userdetails/templates/userdetails-config.yml

Add authenticateOnlyIfLoggedInFilterPattern config to images and userdetails

---

ansible/roles/pipelines_jenkins/templates/jenkins/jobs/Refresh-vocabularies/config.xml.j2

I added this vocabularies to our pipelines-jenkins refresh vocabularies job: https://github.com/gbif/pipelines/blob/dev/livingatlas/configs/la-pipelines-emr.yaml#L138

Refresh pipelines vocabularies

---

ansible/roles/cas5-dbs/tasks/main.yml

Update pymongo to 4.8.0 to fix #838.

Update pymongo version in cas5-dbs

---

ansible/roles/spatial-service/tasks/main.yml

Add aloc.jar to spatial-service

---

ansible/roles/geoserver/tasks/geoserver.yml

With this I get a correct GEOSERVER_CSRF_WHITELIST:

GEOSERVER_CSRF_WHITELIST added to spatial JAVA_OPTS 

---

ansible/roles/spatial-service/tasks/main.yml

Fix for #383.
~TODO: Do a similar thing with  #826 (and other similar missing files) and continue with https://github.com/AtlasOfLivingAustralia/spatial-service/issues/224.~

Add maxent tasks to spatial-service role

---

ansible/roles/ecodata/templates/ecodata-config.properties

Changed API URLs for SciStart config in ecodata

Updated ecodata SciStarter config

---

ansible/roles/alerts/templates/alerts-config.properties

Related issue AtlasOfLivingAustralia/alerts/issues/290

Feature/alerts 4.3.0

---

ansible/roles/species-list/templates/specieslist-webapp-config.properties

See Slack thread for details  - https://atlaslivingaustralia.slack.com/archives/G0104JNLYSH/p1733105260465839

specieslist-webapp (test) - fix for incorrect webservices creds

---

ansible/roles/species-list/templates/specieslist-webapp-config.properties

Revert last change but fix missing var error for `lists_client_id`

specieslist-webapp - fix for LA deployments

---

ansible/roles/biocache-hub/templates/config/grouped_facets_avh.json

AtlasOfLivingAustralia/avh-hub/issues/158

Add optional facet to UI

---

ansible/roles/regions/files/menu-config.json

Update IPA layer ID

---

ansible/roles/image-service/templates/config/image-service-config.yml

- Add configurable tiler params for Image Service 3.0.1 hotfix

Image Service 3.0.1 hotfix

---

ansible/roles/species-list/tasks/vm-tasks.yml

Add default value for db_create

---

ansible/roles/postgresql/tasks/apt.yaml

Use archive for postgresql in focal
